Step2 - 로그인 리팩터링
next-step/atdd-subway-favorite pull request #103
Opened 2021-03-23 12:32 UTC by bbbnam

안녕하세요 성현님
이번 단계도 좀 헤매다가 추상화가 뭘까...
고민하다가 예시로 주신 코드를 곰곰이 생각해보니
이런식인가 싶어서 진행하다보니 코드가 생각보다 잘 나뉘어 지더라구요

그리고 나눌때에도 틈틈이 테스트 코드를 돌려가며 리팩토링 진행하니까
안정감이 생겨서 처음 한번 풀리니까 그 다음부터는 그나마 쉽게 진행했던 것 같습니다.

member 의존성 제거는 인터페이스를 사용하면
CustomUserDetailService에 의존하지 않고 다른 서비스가 와도 UserDetailService만 구현하면
바꿀 수 있을거라 생각해서 의존성 제거 방법으로 사용하였는데요..
이 방법이 맞았으면 좋겠습니다 😥

오늘도 많은 지적 부탁드립니다-!
(ps. 풀리퀘 master쪽으로 잘못 설정해서 close 하고 다시 생성했는데 문제 없겠죠? 😢)

2021-03-24 06:10 UTC, boorownie requested changes
테스트 코드 기반으로 안정적인 리팩터링을 경험하셨다니 대단하십니다! 👍 

테스트 기반으로 인증 로직 리팩터링 잘 수행해주셨습니다 :)
패키지간의 의존성 제거 리팩터링 부분에 대한 처리가 추가로 필요할 것 같아요
관련 코드에 코멘트를 남겨놓았으니 확인해주세요!

2021-03-24 06:10 UTC, boorownie commented on src/test/java/nextstep/subway/auth/session/SessionAuthenticationInterceptorTest.java
> +public class SessionAuthenticationInterceptorTest {
세션 관련 Interceptor 테스트 👍

2021-03-24 06:10 UTC, boorownie commented on src/main/java/nextstep/subway/member/application/UserDetailService.java
> +}
이 인터페이스가 member에 위치할 경우 auth 패키지에서 member 패키지로 의존이 남아있게 되네요ㅠㅠ

2021-03-24 06:10 UTC, boorownie commented on src/main/java/nextstep/subway/auth/ui/common/SecurityContextInterceptor.java
> +public abstract class SecurityContextInterceptor implements HandlerInterceptor {
스레드풀을 사용한다는 가정 하에 재사용 시 이슈가 생길 수 있기 때문에
afterCompletion 메서드에서 SecurityContext를 초기화 해주면 좋을 것 같아요!

2021-03-24 06:10 UTC, boorownie commented on src/main/java/nextstep/subway/auth/ui/common/AuthenticationConverter.java
> +public interface AuthenticationConverter {
추상화 👍

2021-03-24 06:23 UTC, bbbnam commented on src/main/java/nextstep/subway/member/application/UserDetailService.java
> +}
아.. 패키지 의존이 위치에 대한 것도 있었군요..

2021-03-24 12:06 UTC, bbbnam commented
안녕하세요 성현님-!
말씀해주신 부분 리팩토링 해서 다시 리뷰 요청드립니다-😀

음 특히 member 패키지의 의존성을 제거하기 위해서 인터페이스를 만들어서
리팩토링을 해보았는데요.
이렇게 되면, 결국 LoginMember는 UserDetail을 implements를 하게 되어
LoginMember는 auth 패키지에 의존하고
CustomUserDetailsService 도 마찬가지로 UserDetailService 를 implements 하게 되어서
auth 패키지에 의존하게 되는데,

이런경우는 의존한다고 보지 않는 것인가요?
궁금합니다.😮

2021-03-25 01:17 UTC, boorownie approved these changes
피드백 반영 깔끔하게 잘 해주셨습니다 👍 

질문 주신 부분에 대해서 조금 이야기 해 보자면
이번 요구사항의 목적은 모든 의존성을 제거하는것은 아니었습니다.
필요한 의존성은 사용하는게 효율적인 개발을 할 수 있게 도와주는 것 같습니다 :) 

기존에 auth과 member간의 의존은 양방향이었기 때문에 양방향에서 member만 auth에 의존하도록 단방향으로 바꿔보는게 이번 단계의 요구사항 입니다. 즉, 의존성은 최소한으로 필요한 만큼만 가지도록 하고 양방향일 때 한 쪽 방향을 끊어주기 위한 연습이라고 할 수 있죠.

혹시 추가적인 설명이 필요하시면 강의 때 질문 부탁드립니다 :)

제가 제안해 드린 방법을 잘 수행해주셨기 때문에 이번 단계는 머지하고요
이어서 3단계 미션 진행해주시면 될 것 같아요!ㅎㅎ

3단계도 화이팅 입니다! 🚀

2021-03-25 01:17 UTC, boorownie commented on src/main/java/nextstep/subway/auth/domain/UserDetail.java
> +    Integer getAge();
UserDetail의 목적은 로그인에 필요한 인터페이스를 정의하는데 있습니다.
checkPassword는 필요하지만 age나 다른 메서드도 필요한지 확인이 필요할 것 같아요!
그리고 사용자의 고유값을 구분하기 위한 방법으로 email를 사용하지 않을 수 있으니 이 부분도 범용적인 메서드가 필요할 것 같아요 :)

2021-03-25 01:17 UTC, boorownie commented on src/main/java/nextstep/subway/auth/ui/common/AuthenticationInterceptor.java
> +        UserDetail userDetails = userDetailsService.loadUserByUsername(principal);
피드백 반영 👍

2021-03-25 01:17 UTC, merged

2021-03-25 01:20 UTC, bbbnam commented on src/main/java/nextstep/subway/auth/domain/UserDetail.java
> +    Integer getAge();
그렇군요... 단순히 인터페이스화 한다고 LoginMember를 그대로 추상화 해본건데
목적에 따라 필요한 부분만 만들었어도 되는 것이었는데...😯
흐.. ㅠ 쉽지 않군요