Step3 리뷰 요청합니다.
next-step/atdd-subway-favorite pull request #168
Opened 2022-02-09 16:33 UTC by icraft2170

안녕하십니까. 최준우 리뷰어님 Step3는 좀 늦었습니다. ㅠㅠ

Step3를 하면서 막막했던 것이, 서비스는 테스트를 어떻게 해야하지 였습니다. 수업시간에는 테스트 더블 관련된 내용을 배우기는 했지만 아직 익숙해지지 않았던 모양입니다. 혹시 관련 내용에서 추천해주실만한 서적이나 글이 있으면 소개 해주실수 있을까요?

감사합니다.

2022-02-10 13:48 UTC, junwoochoi requested changes
안녕하세요! 
3단계 즐겨찾기 관리 구현 잘해주셨습니다!! 👍 
몇가지 생각해보면 좋을만한 점에 대해 코멘트 달았는데 확인해주시면 감사하겠습니다! 
혹시 더 궁금하신 점이 있으시거나 이해가 안가는 부분이 있으면 언제든 질문주세요! 😃

2022-02-10 13:48 UTC, junwoochoi commented on src/main/java/nextstep/auth/authorization/AuthenticationPrincipalArgumentResolver.java
> +        }
예외처리 👍

2022-02-10 13:48 UTC, junwoochoi commented on src/main/java/nextstep/domain/subway/api/FavoritePathController.java
> +    public ResponseEntity<?> deleteFavorite(@AuthenticationPrincipal LoginMemberImpl member,
```suggestion
    public ResponseEntity<Void> deleteFavorite(@AuthenticationPrincipal LoginMemberImpl member,
```

2022-02-10 13:48 UTC, junwoochoi commented on src/main/java/nextstep/domain/subway/domain/FavoritePath.java
> +    }
무슨 용도의 메소드일까요?

2022-02-10 13:48 UTC, junwoochoi commented on src/main/java/nextstep/domain/subway/service/FavoritePathService.java
> +                .orElseThrow(() -> new IllegalArgumentException("삭제할 수 없는 내용 입니다."));
다른 유저의 즐겨찾기 id를 넣어서 요청하면 다른 유저의 즐겨찾기가 삭제될 염려가 있을 것 같아요 😢

2022-02-10 13:48 UTC, junwoochoi commented on src/test/java/nextstep/domain/subway/domain/FavoritePathTest.java
> +class FavoritePathTest {
domain로직 테스트 👍 👍

2022-02-10 13:48 UTC, junwoochoi commented on src/test/java/nextstep/domain/subway/domain/FavoritePathTest.java
> +    @DisplayName("FavoritePath 유효성 검사 - case 01")
DisplayName에 정확히 어떤 케이스인지 간략히라도 적어주면 다른 사람이 코드를 보기 편하고 유지보수하기도 용이할 것 같네요 :)

2022-02-10 13:48 UTC, junwoochoi commented on src/test/java/nextstep/domain/subway/service/FavoritePathServiceTest.java
> +        favoritePathService = new FavoritePathService(favoritePathRepository, stationRepository, memberRepository);
mock을 이용해서 테스트 잘해주셨네요 👍

2022-02-10 13:48 UTC, junwoochoi commented on src/test/java/nextstep/subway/acceptance/FavoriteAcceptanceTest.java
> +    }
시나리오대로 테스트 잘해주셨습니다 :)

2022-02-10 13:48 UTC, junwoochoi commented on src/main/java/nextstep/domain/subway/domain/FavoritePath.java
> +    private Member member;
Favorite객체에서 Member객체에 직접 참조하여 구현해보셨네요 😃
직접 참조를 하면 Favorite객체를 통해 member객체 자체에 바로 접근하기에는 좋지만, 의존성이 깊어지게 되면서 객체간의 결합도가 높아질 수 있답니다 :)

둘이 다른 라이프 사이클을 가진다고 생각되면 과감하게 memberId만 가지는 형식으로 간접참조하도록 바꿔보시는 것도 좋은 연습이 될 것 같습니다!

https://youtu.be/dJ5C4qRqAgA?t=3905

요 영상이 도움이 될 것 같습니다 :)

2022-02-10 14:03 UTC, junwoochoi commented on src/test/java/nextstep/domain/subway/service/FavoritePathServiceTest.java
> +        favoritePathService = new FavoritePathService(favoritePathRepository, stationRepository, memberRepository);
@icraft2170 테스트 더블에 관련된 마틴 파울러의 게시글인데, 한번 같이 추천드려봅니다!

https://martinfowler.com/articles/mocksArentStubs.html

2022-02-10 14:31 UTC, icraft2170 commented on src/main/java/nextstep/domain/subway/domain/FavoritePath.java
> +    private Member member;
사실 오늘 수업에서 들어보면서 이런 것도 있구나 처음 알았던것 같아요.. 반성하게 됩니다 ㅠ 당연히 참조로 연결해야 한다는 고정 관념이 깨진 하루였습니다.

2022-02-10 14:32 UTC, icraft2170 commented on src/test/java/nextstep/domain/subway/service/FavoritePathServiceTest.java
> +        favoritePathService = new FavoritePathService(favoritePathRepository, stationRepository, memberRepository);
감사합니다~! 읽어 보겠습니다!!

2022-02-12 04:16 UTC, junwoochoi approved these changes
안녕하세요!! 
3단계 미션까지 열심히 진행하시느라 수고 많으셨습니다!!
인수테스트 흐름을 따라서 열심히 작성해주시고, 피드백 적용시점에도 테스트를 먼저 작성하는 모습이 인상적이었어요 👍 👍 👍 
다음 주차 미션도 화이팅 입니다!!! 🥇

2022-02-12 04:16 UTC, junwoochoi commented on src/main/java/nextstep/domain/subway/domain/FavoritePath.java
> +        }
피드백 적용 👍

2022-02-12 04:16 UTC, junwoochoi commented on src/test/java/nextstep/domain/subway/domain/FavoritePathTest.java
> +    @DisplayName("FavoritePath 유효성 검사 - 즐겨찾기 신청 멤버의 데이터가 null 인 경우")
안전하게 함께 체크하는 것도 좋은 것 같아요 :)

2022-02-12 04:16 UTC, junwoochoi commented on src/test/java/nextstep/domain/subway/service/FavoritePathServiceTest.java
> +
테스트 코드 먼저 작성 💯

2022-02-12 04:16 UTC, merged