Step1
next-step/atdd-subway-favorite pull request #169
Opened 2022-02-09 17:10 UTC by gashe-soo

안녕하세요 리뷰어님, 리뷰요청드립니다. 

질문 드립니다. 
요약 : TokenInterceptor에서 convert/authenticate는  private 메소드가 적당하지 않을까 합니다. 리뷰어님 생각이 듣고 싶어요.
> Interceptor Test에선 의도적으로 convert/ authenticate를 테스트하는 건가요? 
구현하면서 보니 해당 함수는 Override해야할 대상도 아니고 외부로 노출해야 할 메소드가 아닌데, public으로 만들어서 테스트를 하고 있더라고요. 
그러고서 prehandle() 함수에서도 이를 사용하고 있는데,  convert 함수 자체를 모킹하는 것이 아닌 내부 로직을 모킹하더라고요. 그건 결국 prehandle 뿐만 아니라 내부에서 사용하는 함수까지 테스트하는 셈이 되어버려서 convert() 테스트가 통과되지 않으면 prehandle 테스트를 사용할 수 없다로 되어버리더군요. 
그래서 불필요하지만 교육목적으로 사용하고 있는 것인가 생각이 들었습니다. 

의도적으로 기존의 코드는 거의 건들지 않습니다. 
많은 피드백 부탁드립니다. 🙇‍♀️

2022-02-10 22:31 UTC, kang-hyungu commented
> > Interceptor Test에선 의도적으로 convert/ authenticate를 테스트하는 건가요?
> > 구현하면서 보니 해당 함수는 Override해야할 대상도 아니고 외부로 노출해야 할 메소드가 아닌데, public으로 만들어서 테스트를 하고 있더라고요.
> > 그러고서 prehandle() 함수에서도 이를 사용하고 있는데,  convert 함수 자체를 모킹하는 것이 아닌 내부 로직을 모킹하더라고요. 그건 결국 prehandle 뿐만 아니라 내부에서 사용하는 함수까지 테스트하는 셈이 되어버려서 convert() 테스트가 통과되지 않으면 prehandle 테스트를 사용할 수 없다로 되어버리더군요.
> > 그래서 불필요하지만 교육목적으로 사용하고 있는 것인가 생각이 들었습니다.

말씀하신 것처럼 테스트 때문에 접근제어자를 public으로 두는 것은 적절해보이진 않네요.
학습 목적으로 기능의 일부 메서드를 테스트한다는 개념으로 접근하시기 바랍니다.
접근제어자를 public 대신에 default로 두는 방법도 있으니 참고하세요.

2022-02-10 22:32 UTC, kang-hyungu requested changes
안녕하세요 이수님. 만나서 반갑습니다. 리뷰어 강현구입니다.
1단계 미션 심플하게 잘 진행해주셨네요.
몇가지 간단한 피드백 남겼는데 참고하세요.

2022-02-10 22:32 UTC, kang-hyungu commented on src/test/java/nextstep/subway/acceptance/MemberAcceptanceTest.java
> +     * When 회원 생성을 요청
현재 테스트 시나리오는 어떤 것을 체크하는게 목적인가요?
하나의 테스트에서 crud를 점검해야 되는 이유가 있을까요?

2022-02-11 14:40 UTC, gashe-soo commented on src/test/java/nextstep/subway/acceptance/MemberAcceptanceTest.java
> +     * When 회원 생성을 요청
>인수 테스트를 통합
인수 테스트를 통합하는 경험을 하기 위한 요구사항입니다.
아래의 인수 조건에 맞게 인수 테스트를 리팩터링 하세요.

이번 미션 중 하나여서 통합해서 진행했습니다.

2022-02-12 07:08 UTC, kang-hyungu commented on src/test/java/nextstep/subway/acceptance/MemberAcceptanceTest.java
> +     * When 회원 생성을 요청
제 질문의 의도는 https://github.com/next-step/atdd-subway-favorite/pull/169#discussion_r804174101 에 남긴 것과 동일합니다.
어떤 것을 테스트하려는지 테스트 시나리오로 파악하기 어려워서 남긴 코멘트였습니다.

2022-02-12 07:09 UTC, kang-hyungu approved these changes
이수님 피드백 반영 잘 해주셨습니다.
pr은 머지 처리하겠습니다. 다음 미션 진행해주세요.

2022-02-12 07:09 UTC, merged