3단계 - 즐겨찾기 기능 구현
next-step/atdd-subway-favorite pull request #181
Opened 2022-02-12 11:09 UTC by testrace

안녕하세요 리뷰어님 😀
3단계 리뷰 요청 드립니다!

질문이 있는데요!

1.
Favorite 엔티티와 Member 엔티티의 관계를 단방향으로 설정했습니다. 
처음엔 양방향으로 설정해서 Line <-> Sections 와 동일한 방식으로 하려했지만,
member에서 favorites 를 참조할 일이 당장 필요할 것 같진 않아 단방향으로 설정했고, favorite의 일급 컬렉션도 만들지 않았습니다. 
리뷰어님은 객체간의 연관관계에서 단방향, 양방향 설정하실 때 어떠한 기준 같은게 있으신지 궁금합니다!

2.
인수 테스트를 작성할때 CRUD 각각 테스트를 두지 않고 통합된 형태로 테스트 코드를 작성했는데요
통합된 인수테스트에서 테스트를 실패하게되면 원인을 찾는데 직관적이지 않아서 조금 불편하더라구요
CRUD에 해당하는 인수테스트를 각각 만들어두고, 통합된 인수테스트도 따로 두는게 좋지 않을까 싶었습니다.
리뷰어님은 인수테스트 코드를 어떻게 관리하시는지 궁금합니다!

2022-02-13 08:36 UTC, junwoochoi requested changes
안녕하세요! 3단계 구현 및 테스트 정말 잘해주셨네요!
특히 테스트 픽스처를 잘 생성해주시고, 주석으로 지도를 잘 그려주셔서 다른 팀원들도 이어서 코드 유지보수를 정말 잘할 수 있을 것 같아요 👍 👍 

몇가지 생각해볼 점에 대해 코멘트 달아보았는데 확인해보시고, 궁금한 점이나 이해가 안가는 코멘트가 있다면 질문주시면 감사하겠습니다 👍 

---

>Favorite 엔티티와 Member 엔티티의 관계를 단방향으로 설정했습니다.
처음엔 양방향으로 설정해서 Line <-> Sections 와 동일한 방식으로 하려했지만,
member에서 favorites 를 참조할 일이 당장 필요할 것 같진 않아 단방향으로 설정했고, favorite의 일급 컬렉션도 만들지 않았습니다.
리뷰어님은 객체간의 연관관계에서 단방향, 양방향 설정하실 때 어떠한 기준 같은게 있으신지 궁금합니다!

저 같은 경우 일단 단방향으로 설정을 해놓고, 추후 사용하면서 양방향이 필요한 케이스에만 양방향을 설정하려고 노력하는 편입니다! 
양방향으로 설정하면 JPA의 이점을 활용할 수는 있지만 불필요한 참조는 복잡도를 높일 수도 있다고 생각합니다. 물론 정답은 없어서 사용해보시면서 편한 쪽을 선택하시면 됩니다 :)

>인수 테스트를 작성할때 CRUD 각각 테스트를 두지 않고 통합된 형태로 테스트 코드를 작성했는데요
통합된 인수테스트에서 테스트를 실패하게되면 원인을 찾는데 직관적이지 않아서 조금 불편하더라구요
CRUD에 해당하는 인수테스트를 각각 만들어두고, 통합된 인수테스트도 따로 두는게 좋지 않을까 싶었습니다.
리뷰어님은 인수테스트 코드를 어떻게 관리하시는지 궁금합니다!

저 같은 경우 통합 테스트를 관리하는 것보다는 각각의 케이스를 따로 관리하는 걸 선호하는 편이긴 합니다. 말씀해주신 것처럼 통합된 테스트 따로, 각각의 인수테스트 따로도 관리 코스트는 증가하지만, 안전한 테스트 방법이 될 수 있을 것 같아요! 여러가지 해보시면서 선호하시는 방법을 사용해보시면 좋겠네요!

2022-02-13 08:36 UTC, junwoochoi commented on README.md
> +        Then 즐겨찾기 삭제 실패한다
실패 케이스도 꼼꼼히 테스트 👍

2022-02-13 08:36 UTC, junwoochoi commented on src/main/java/nextstep/auth/authorization/AuthenticationPrincipalArgumentResolver.java
> +        }
👍 👍 👍

2022-02-13 08:36 UTC, junwoochoi commented on src/main/java/nextstep/favorite/applicataion/FavoriteService.java
> +        }
👍  상세한 익셉션 클래스를 만들어서 예외를 던져보느 것도 좋았을 것 같네요 😄

2022-02-13 08:36 UTC, junwoochoi commented on src/main/java/nextstep/favorite/domain/Favorite.java
> +    protected Favorite() {
👍  protected로 안전한 기본 생성자 생성

2022-02-13 08:36 UTC, junwoochoi commented on src/main/java/nextstep/favorite/domain/Favorite.java
> +    private Member member;
Favorite에서 Member를 직접참조하여 구현해주셨네요 👍 

직접 참조를 하면 Favorite객체를 통해 member객체 자체에 바로 접근하기에는 좋지만, 의존성이 깊어지게 되면서 객체간의 결합도가 높아질 수 있답니다 :)

둘이 다른 라이프 사이클을 가진다고 생각되면 과감하게 memberId만 가지는 형식으로 간접참조하도록 바꿔보시는 것도 좋은 연습이 될 것 같습니다!

https://youtu.be/dJ5C4qRqAgA?t=3905

요 영상이 도움이 될 것 같습니다 :)

2022-02-13 08:36 UTC, junwoochoi commented on src/main/java/nextstep/favorite/domain/Favorite.java
> +    @ManyToOne(cascade = CascadeType.PERSIST)
Favorite이 저장될때 member객체가 함께 PERSIST되는게 의도하신 라이프 사이클이 맞을까요?
둘의 라이프사이클이 다르니까 cascade타입도 고민이 필요해보여요

2022-02-13 08:36 UTC, junwoochoi commented on src/main/java/nextstep/favorite/domain/Favorite.java
> +    private Station targetStation;
여기서도 cascade타입을 MERGE로 주셨는데, 과연 Station을 수정하려고할 때 Favorite을 통하게되는게 과연 안전하고, 의도된 라이프사이클일 지 고민해보시면 좋을 것 같습니다 😃

2022-02-13 08:36 UTC, junwoochoi commented on src/test/java/nextstep/subway/acceptance/FavoriteAcceptanceTest.java
> +     */
테스트 픽스처 가독성 좋아요! 💯

2022-02-13 08:36 UTC, junwoochoi commented on src/test/java/nextstep/subway/acceptance/FavoriteAcceptanceTest.java
> +    }
다양한 예외도 꼼꼼히 체크 👍 👍

2022-02-13 08:36 UTC, junwoochoi commented on src/test/java/nextstep/subway/unit/FavoriteServiceTest.java
> +@SpringBootTest(webEnvironment = SpringBootTest.WebEnvironment.RANDOM_PORT)
@DataJpaTest 라는 애노테이션도 있으니 나중에 사용해보시면 좋을 것 같아요 👍

2022-02-13 11:00 UTC, testrace commented on src/main/java/nextstep/favorite/domain/Favorite.java
> +    private Member member;
참고링크 감사합니다!
영상을 보고 많은 것을 알 수 있었습니다!
현재 도메인 모델에서는 직접 참조를 할 이유가 전혀 없다고 판단이 되네요!
본질적으로 결합도가 높을 이유도, 라이프 사이클이나 제약사항도 공유하지 않으니 간접 참조로 변경하는 것 이 맞을 것 같아요!

조금 다른 이야기인데요, 어디선가 애그리거트라는 말을 들어본 적이 있습니다.
미션에서 사용되는 Favorite 객체와 Member 객체는 서로 다른 애그리거트에 속하니 직접 참조할 이유가 없는 것과 같은 맥락이라고 생각될까요?
제가 잘못 알고 있는거라면 정정 부탁드립니다 😀

2022-02-13 11:04 UTC, testrace commented on src/main/java/nextstep/favorite/domain/Favorite.java
> +    @ManyToOne(cascade = CascadeType.PERSIST)
cascade를 잘 몰라서.. Section 에 있던걸 그대로 복붙하다보니 이렇게 됐어요 😭

2022-02-13 12:40 UTC, testrace commented on src/main/java/nextstep/favorite/domain/Favorite.java
> +    private Station targetStation;
cascade는 삭제해 두었습니다. 
ManyToOne.java의 javadoc을 읽어보니 cascade는 optional이고, 기본적으로는 동작하지 않는다고해서 
cascade 옵션을 삭제하면 Station의 변경에 영향을 받지 않겠다고 생각됩니다. 
혹시 잘못 이해한 부분이 있다면 알려주세요 :)

2022-02-13 14:52 UTC, merged

2022-02-14 12:30 UTC, testrace commented on src/main/java/nextstep/favorite/domain/Favorite.java
> +    private Long memberId;
감사합니다 😀