🚀 1단계 - 토큰 기반 로그인 구현
next-step/atdd-subway-favorite pull request #196
Opened 2022-02-13 17:12 UTC by thxwelchs

안녕하세요 리뷰어님, 이번 미션에서 만나게 되어 영광입니다~!

이번 미션 리뷰 잘 부탁드리겠습니다.

2022-02-14 23:14 UTC, catsbi requested changes
안녕하세요 태훈님 3주차 미션을 함께하게 된 이한솔이라고 합니다. 👍 
코드는 전체적으로 깔끔하게 잘 작성해주셨고 가독성도 나쁘지 않았습니다 💯 
다만, member와 auth 패키지간의 의존성이 남아있는 부분들이 있고, 추상화가 필요한 부분이 있어서
코멘트 남겨드렸으니 리뷰 확인후 다시 리뷰요청해주세요 !

2022-02-14 23:14 UTC, catsbi commented on src/main/java/nextstep/auth/AuthConfig.java
> +    private ObjectMapper objectMapper;
final 키워드를 붙혀주면 생성자 주입시 해당 스프링 빈을 찾지 못할 경우 애플리케이션 구동단계에서 에러를 내뱉기에 좀 더 안전할 수 있어요 😄

2022-02-14 23:14 UTC, catsbi commented on src/main/java/nextstep/auth/AuthConfig.java
>      private CustomUserDetailsService userDetailsService;
CustomUserDetailService라는 클래스는 구현체로 보이는데 좀 더 추상화가 가능하지 않을까요??
OOP 패러다임 중 DIP 패러다임이 있죠. 구체화가 아닌 추상화에 의존하라는 것인데요, 이를 지켜서 유연성과 확장성을 늘려볼 수 있을 것 같아요!

2022-02-14 23:14 UTC, catsbi commented on src/main/java/nextstep/auth/authentication/AuthenticationInterceptor.java
> +        LoginMember userDetails = userDetailsService.loadUserByUsername(principal);
LoginMember객체는 member 패키지의 도메인이죠. auth에서 member에 의존성의 흐름이 생긴거 같아요. 이를 끊어줄 순 없을까요?

2022-02-14 23:14 UTC, catsbi commented on src/main/java/nextstep/auth/authentication/AuthenticationInterceptor.java
> +    private CustomUserDetailsService userDetailsService;
- @Autowired 애노테이션이 없어도 자동으로 주입이 되는데 어떻게 되는 것일까요? 언제부터 스프링에서 이런 지원을 해주는 걸까요!?
-  여기도 좀 더 추상화의 의존할 수 있을 것 같아요 👍

2022-02-14 23:14 UTC, catsbi commented on src/main/java/nextstep/auth/authentication/AuthenticationInterceptor.java
> +    protected void checkAuthentication(LoginMember userDetails, AuthenticationToken token) {
여기도 LoginMember객체가 매개변수 타입으로 사용되고 있습니다. 이 의존성을 끊어주기 위해선 어떻게 해야할까요!

2022-02-14 23:14 UTC, catsbi commented on src/main/java/nextstep/auth/authentication/SessionAuthenticationInterceptor.java
> +public class SessionAuthenticationInterceptor extends AuthenticationInterceptor {
공통 모듈 상속화 👍

2022-02-14 23:14 UTC, catsbi commented on src/main/java/nextstep/auth/authentication/TokenAuthenticationInterceptor.java
> +    private CustomUserDetailsService userDetailsService;
이 부분도 추상화가 가능할 것 같아요!

2022-02-14 23:14 UTC, catsbi commented on src/main/java/nextstep/auth/authorization/AuthenticationPrincipalArgumentResolver.java
> +        if (securityContext.hasNotAuthentication()) {
값을 가져와 연산하는게 아닌 메서드를 이용해 메세지를 주고받도록 설계하셨네요 좋습니다 👍

2022-02-16 12:13 UTC, thxwelchs commented on src/main/java/nextstep/auth/authentication/AuthenticationInterceptor.java
> +    private CustomUserDetailsService userDetailsService;
Spring 4.3부터 `@Autowired` 어노테이션을 생략하더라도 어떠한 스프링 빈 클래스에 생성자가 하나뿐이고 생성자로 받게되는 매개변수들이 빈으로 등록되어있는 타입의 매개변수라면 그 빈을 자동으로 주입해주도록 변경된것으로 알고있습니다~

https://spring.io/blog/2016/03/04/core-container-refinements-in-spring-framework-4-3

2022-02-16 12:16 UTC, thxwelchs commented on src/main/java/nextstep/auth/AuthConfig.java
> +    private ObjectMapper objectMapper;
[5eb7789](https://github.com/next-step/atdd-subway-favorite/pull/196/commits/5eb77894ec1e956f41d764af40994e29b9a65f96) 반영했습니다

2022-02-16 12:17 UTC, thxwelchs commented on src/main/java/nextstep/auth/AuthConfig.java
>      private CustomUserDetailsService userDetailsService;
[a7d17fc](https://github.com/next-step/atdd-subway-favorite/pull/196/commits/a7d17fc29857253f6335b9b8924c3ea42b8f6dac) 반영했습니다

2022-02-16 12:19 UTC, thxwelchs commented on src/main/java/nextstep/auth/authentication/AuthenticationInterceptor.java
> +        LoginMember userDetails = userDetailsService.loadUserByUsername(principal);
다른 Bounded Context더라도 [a7d17fc](https://github.com/next-step/atdd-subway-favorite/pull/196/commits/a7d17fc29857253f6335b9b8924c3ea42b8f6dac)에서 반영했습니다. (의존성 역전으로 흐름 바꿈)

2022-02-16 12:19 UTC, thxwelchs commented on src/main/java/nextstep/auth/authentication/AuthenticationInterceptor.java
> +    protected void checkAuthentication(LoginMember userDetails, AuthenticationToken token) {
마찬가지로 [a7d17fc](https://github.com/next-step/atdd-subway-favorite/pull/196/commits/a7d17fc29857253f6335b9b8924c3ea42b8f6dac) 에서 반영했습니다

2022-02-17 05:56 UTC, catsbi approved these changes
태훈님 피드백 빨리 반영해주셨네요!
의존성의 흐름도 끊어지고 추상화도 적절히 잘 해주셨습니다. 바로 다음단계 진행해주시면 될 것 같습니다. 😄

2022-02-17 05:56 UTC, merged