Step2 인증 로직 리팩터링
next-step/atdd-subway-favorite pull request #209
Opened 2022-02-15 15:58 UTC by dk-ko

안녕하세요 준우님! 2단계 PR 다시 올립니다

요구사항을 제가 맞게 파악한 것인지 모르겠는데
- [ ] 1,2단계에서 구현한 인증 로직에 대한 리팩터링을 진행하세요
- [x] 내 정보 수정 / 삭제 기능을 처리하는 기능을 구현하세요.
- [x] Controller에서 애너테이션을 활용하여 Login 정보에 접근

아래 두가지의 경우 이전 단계(#201, #205) 에서 이미 구현을 한 것 같아서 
인증 로직에 대한 리팩터링 진행해서 올렸습니다 
코드 수정사항이 적어서 의도에 맞게 진행한건지 모르겠네요..!

이번 과정도 잘 부탁드립니다 🙇

2022-02-16 12:18 UTC, junwoochoi requested changes
안녕하세요 :) 2번째 미션 진행해주신 부분 잘 봤습니다.
몇가지 더 고민해보시고, 수정해보시면 좋을 것 같은 부분과 관련해서 코멘트 남겼는데 확인 부탁드립니다 😃

2022-02-16 12:18 UTC, junwoochoi commented on src/main/java/nextstep/auth/authentication/AuthenticationConverter.java
> +        return new Authentication(userDetails);
SRP위반으로 보입니다. 
`AuthenticationConverter`객체는 convert기능에 집중하고, 인증은 다른 객체에서 책임을 가지게 하면 더 좋을 것 같은데 어떨까요?

2022-02-16 12:18 UTC, junwoochoi commented on src/main/java/nextstep/auth/authentication/SessionAuthenticationInterceptor.java
>  import nextstep.member.application.CustomUserDetailsService;
현재 auth <-> member 가 서로 의존하고 있는데, auth -> member로 흐르는 의존성을 끊어서 의존성 흐름이 ` auth <---- member` 로 단방향으로 흐르도록 해볼 수 있을까요?

2022-02-16 12:18 UTC, junwoochoi commented on src/main/java/nextstep/auth/authentication/SessionAuthenticationInterceptor.java
> +public class SessionAuthenticationInterceptor implements HandlerInterceptor, AuthenticationConverter {
상속보다는 합성을 권해드리는데요, SessionConverter를 따로 구현을 하신 뒤, Interceptor객체에서는 해당 converter를 의존성 주입받아 사용해보시면 어떨까요? 참고할만한 게시글 공유드립니다 :)
https://velog.io/@ljinsk3/%EC%83%81%EC%86%8D%EA%B3%BC-%ED%95%A9%EC%84%B1

2022-02-16 12:18 UTC, junwoochoi commented on src/main/java/nextstep/auth/authentication/TokenAuthenticationInterceptor.java
> +    private ObjectMapper objectMapper;
의존성 주입 👍

2022-02-16 12:18 UTC, junwoochoi commented on src/main/java/nextstep/auth/authorization/SessionSecurityContextPersistenceInterceptor.java
> +//public class SessionSecurityContextPersistenceInterceptor implements HandlerInterceptor {
사용하지 않는 코드 및 주석은 과감히 제거해주세요 :)

2022-02-16 12:18 UTC, junwoochoi commented on src/main/java/nextstep/auth/authorization/SessionSecurityContextPersistenceInterceptor.java
> +//    }
사용하지 않는 코드 및 주석은 과감히 제거해주세요 :)

2022-02-16 12:18 UTC, junwoochoi commented on src/main/java/nextstep/auth/authentication/SessionAuthenticationInterceptor.java
>  import nextstep.member.application.CustomUserDetailsService;
[우아한 객체지향 세미나 - 패키지 의존 문제 해결](https://youtu.be/dJ5C4qRqAgA?t=2941) 요 동영상이 도움이 될 수 있을까요

2022-02-18 02:22 UTC, dk-ko commented on src/main/java/nextstep/auth/authentication/AuthenticationConverter.java
> +        return new Authentication(userDetails);
인증을 UserAuthentication 객체로 분리 했습니다

2022-02-18 12:44 UTC, junwoochoi requested changes
안녕하세요! 아직 auth와 member 패키지의 양방향 의존이 남아있는 부분이 있어 코멘트 드렸습니다!
혹시 이해가 안가는 부분이 있다면 편히 질문 주세요😃

2022-02-20 09:18 UTC, junwoochoi approved these changes
안녕하세요! 피드백 적용해주신 부분 확인했습니다!
적용해보시면서 지난번 질문주신 내용이 이해가 되셨을 지 궁금하네요 😄 
혹시 더 궁금한 점이 있으면 언제든 질문주시고, 다음 미션도 화이팅입니다!~~ 💪

2022-02-20 09:18 UTC, junwoochoi commented on src/main/java/nextstep/auth/authentication/UserAuthentication.java
> +    private final UserDetailsService userDetailsService;
👍 👍

2022-02-20 09:18 UTC, junwoochoi commented on src/main/java/nextstep/auth/authentication/UserAuthentication.java
> +        final UserDetails userDetails = userDetailsService.loadUserByUsername(principal);
💯  인터페이스를 활용해 기존 member에서 가져오던 의존성을 역전시키셨네요 :)

2022-02-20 09:29 UTC, merged