Step3 리뷰 요청드립니다.
next-step/atdd-subway-favorite pull request #220
Opened 2022-02-18 16:51 UTC by kimuno89

Step2에서 말씀해주신 최상위 User 객체를 만들어서 구현에 대하여 질문이 있습니다.
User (최상위) / UserDetail (auth) / LoginForm (member)가 있다면 User는 어느 패키지에 존재하는게 좋은걸까요?

원래는 auth에 만들어서 구현을 했다가 현재는 삭제하고 step2코드를 그대로 사용하고 있습니다.

2022-02-19 01:08 UTC, catsbi requested changes
윤호님 3단계 구현하시느라 고생하셨습니다 🥇 
피드백이 필요한 부분과, 질문주신 내용에 대해 코멘트 남겨드렸으니 확인해주세요!
그리고 현재 AuthAcceptanceTest가 실패하는게 있는것 같은데 확인이 필요할 것 같네요 😢 
확인 후 다시 리뷰요청 해주세요!

2022-02-19 14:02 UTC, kimuno89 commented on src/main/java/nextstep/subway/applicaion/FavoriteService.java
> +                .orElseThrow(IllegalArgumentException::new);
MemberService에 findMember가 존재해서 findById를 새로 만드는거에 대한 거부감이 있어서
Repository를 바로 사용했습니다.

코드 일관성을 위해 Service에 findById를 만드는게 더 좋은 선택일까요?

2022-02-19 14:03 UTC, kimuno89 commented on src/main/java/nextstep/subway/domain/Favorite.java
> +    private Member member;
다음 미션에 적용해보겠습니다!

2022-02-21 08:45 UTC, catsbi commented on src/main/java/nextstep/subway/applicaion/FavoriteService.java
> +                .orElseThrow(IllegalArgumentException::new);
@kimuno89 
리포지토리를 통해 직접조회할 경우, 해당 엔티티가 존재하지 않거나 하는 상황이나 기타 상황에 대한 책임을 해당 리포지토리를 의존하는 서비스계층에서 책임을 져야하는데 FavoriteService는 회원 엔티티에 대한 검색 책임을 지는건 적절치 못하다고 보입니다 😢

2022-02-21 08:56 UTC, catsbi approved these changes
윤호님 3단계 구현 및 피드백 반영까지 잘 해주셨습니다. 💯 
피드백이 필요한 부분에 대해서는 코멘트를 남겨드렸으니, 차후 다음 주차 미션을 진행하면서 유념해두시면 좋을 것 같아요!  미션 진행하느라 고생 많으셨습니다. 이만 머지하겠습니다. 🥇

2022-02-21 08:56 UTC, catsbi commented on src/main/java/nextstep/subway/domain/Favorite.java
> +import javax.persistence.*;
여기도 `*` 이 있네요 😢

2022-02-21 08:56 UTC, catsbi commented on src/main/java/nextstep/auth/authentication/User.java
> +public class User {
이렇게 구체클래스 User를 만들라는 의미가 아니였습니다. 구체 클래스를 상위 클래스로 두는 행위는 하위 객체에서 상위 객체의 기능 뿐 아니라 책임까지 상속하기에 정말 필요한 경우가 아니라면, 지양하는게 좋습니다. 공통적인 상태나 메서드가 골격으로 존재해야하는 경우 추상 클래스(abstract)를 쓸 수도 있지만, 왠만해서는 인터페이스 설계를 통해 `상태` 가 아닌 `행위`를 제공하도록 하는게 좋습니다.

2022-02-21 08:56 UTC, merged