Step2 인증 로직 리팩터링
next-step/atdd-subway-favorite pull request #232
Opened 2022-02-20 18:10 UTC by songsimo

안녕하세요, 리뷰어님! 이번에도 잘 부탁드립니다.

이번 미션은 하면서도 특히 자신이 없네요.

Auth와 Member와의 의존성 패키지를 분리한게 인터페이스를 이용하여 구현하는게 맞는건지 과제 힌트로 준 영상에서는 인터페이스가 아닌 개발에서의 추상화는 변하지 않는 것을 이야기 했는데 아무리 생각해도 해당 방법으로는 떠오르지 않아서요...ㅠ ㅠ
패키지에도 의존성을 고민하는 내용은 생각지도 못했는데 이번에 많이 배우게 되었습니다.

많이 지적 받을 거 같은데 미리 잘 부탁드립니다... 감사합니다!! 😅😅😅

잘못된 저장소 관리로 프로젝트를 다시 받아서 작성하다보니 히스토리를 날렸어요;;;

2022-02-21 07:24 UTC, boorownie requested changes
안녕하세요! 2단계 미션 구현 하시느라 고생 많으셨습니다.
우선 2단계 요구사항이 머리로는 이해하는데 어렵진 않지만 막상 하려고 했을 때 뭐부터해야할 지 고민이 들 수 있는 요구사항이라고 생각해요. 그래서 많은 코멘트를 드리기 보다는 하나의 코멘트를 드리고 그 코멘트의 요구사항을 해결한 후 그와 유사한 형태로 다른 부분에서 리팩터링을 해보시는 것이 좋을 것 같아서 그런 방향으로 우선 코멘트를 남겨보았습니다. 

우선 코멘트 남겨드린 부분에 대해서 추상화를 진행해보시고
다시 리뷰요청 해주시면 이후 다른 부분에 대해서도 코멘트를 남겨드릴게요!

2022-02-21 07:24 UTC, boorownie commented on src/test/java/nextstep/common/Steps.java
> +public class Steps {
공통의 스텝은 별도의 스텝 클래스로 분리해주셨군요 👍

2022-02-21 07:24 UTC, boorownie commented on src/test/java/nextstep/subway/acceptance/StationAcceptanceTest.java
> -        assertThat(response.statusCode()).isEqualTo(HttpStatus.CREATED.value());
인수 테스트 중복 제거를 통한 리팩터링 👍

2022-02-21 07:24 UTC, boorownie commented on src/test/java/nextstep/member/MemberSteps.java
> +package nextstep.member;
테스트 패키지 구분을 해주셨네요 👍

2022-02-21 07:24 UTC, boorownie commented on src/main/java/nextstep/auth/authentication/SessionAuthenticationInterceptor.java
>  import static nextstep.auth.context.SecurityContextHolder.SPRING_SECURITY_CONTEXT_KEY;
의존 제거는 잘 해주셨는데 import에는 그대로 남아있는 것 같아요ㅠㅠ

2022-02-21 07:24 UTC, boorownie commented on src/main/java/nextstep/auth/authentication/AuthenticationInterceptor.java
> +		UserDetails userDetails = userDetailsService.loadUserByUsername(principal);
UserDetailsService와 UserDetails를 통해서 member에 대한 의존을 제거해주셨네요 👍

2022-02-21 07:24 UTC, boorownie commented on src/main/java/nextstep/auth/authorization/SecurityContextInterceptor.java
> +public abstract class SecurityContextInterceptor implements HandlerInterceptor {
인증 객체를 활용하여 처리하는 로직에 대한 추상화를 해주셨네요!
SessionSecurityContextPersistenceInterceptor와 TokenSecurityContextPersistenceInterceptor는 afterCompletion 말고도 비슷한 단계를 많이 가지고 있어요! 예를 들면 인증 객체가 유효한지 검사 후 유효 했을 때의 처리와 유효하지 않았을 때의 처리 등

preHandle 메서드 내에서 인증에 성공했을 때 처리하는 객체와 실패했을 때 처리하는 객체를 추상화 해서 SessionSecurityContextPersistenceInterceptor와 TokenSecurityContextPersistenceInterceptor에서 각각 구현해준다면 이 역시도 추상화의 대상이 되지 않을까요?

2022-02-21 07:24 UTC, boorownie commented on src/main/java/nextstep/auth/authentication/SessionAuthenticationInterceptor.java
> +    SessionAuthenticationConverter sessionAuthenticationConverter;
SessionAuthenticationConverter를 SessionAuthenticationInterceptor의 멤버 변수로 두고 사용하기 보다는
AuthenticationInterceptor에서 AuthenticationConverter를 멤버 변수로 두고
주입을 할 때 SessionAuthenticationInterceptor생성 시 SessionAuthenticationInterceptor를 주입하는 형태로 진행해도 좋았을 것 같아요!
이렇게 되면 authenticationConverter.convert() 메서드를 호출하는 로직이 AuthenticationInterceptor 내부에 있어야 하기 때문에 preHandle() 메서드는 SessionAuthenticationInterceptor가 아닌 AuthenticationInterceptor에 위치해야 하겠네요 :)

2022-02-21 11:05 UTC, songsimo commented on src/main/java/nextstep/auth/authentication/SessionAuthenticationInterceptor.java
>  import static nextstep.auth.context.SecurityContextHolder.SPRING_SECURITY_CONTEXT_KEY;
앗... 브랜치 잘 못되고 제대로 확인을 안했네요;;;; 😓😓

2022-02-21 11:05 UTC, songsimo commented on src/main/java/nextstep/auth/authentication/SessionAuthenticationInterceptor.java
>  import static nextstep.auth.context.SecurityContextHolder.SPRING_SECURITY_CONTEXT_KEY;
앗... 브랜치 잘 못되고 제대로 확인을 안했네요;;;; 😓😓

2022-02-21 15:50 UTC, songsimo commented on src/main/java/nextstep/auth/authentication/SessionAuthenticationInterceptor.java
> +    SessionAuthenticationConverter sessionAuthenticationConverter;
> SessionAuthenticationConverter를 SessionAuthenticationInterceptor의 멤버 변수로 두고 사용하기 보다는 AuthenticationInterceptor에서 AuthenticationConverter를 멤버 변수로 두고 주입을 할 때 SessionAuthenticationInterceptor생성 시 SessionAuthenticationInterceptor를 주입하는 형태로 진행해도 좋았을 것 같아요! 이렇게 되면 authenticationConverter.convert() 메서드를 호출하는 로직이 AuthenticationInterceptor 내부에 있어야 하기 때문에 preHandle() 메서드는 SessionAuthenticationInterceptor가 아닌 AuthenticationInterceptor에 위치해야 하겠네요 :)

----------------------

해당 리뷰에 대해서 코드 수정 중 의문이 생겨서 질문 드려요.

1. 추상화한 AuthenticationConverter 인터페이스의 convert() 메소드를 구현한 TokenAuthenticationConverter.convert() 메소드 때문에 인터페이스에 throws IOExcetion을 붙였는데 어느 한 구현 클래스 때문에 기능쪽에 throws 예외를 붙이는게 좋은건지 궁금해요.
2. 예외를 붙이는게 맞다면 커스텀 예외를 만들어 붙이는게 좋을까요?

2022-02-22 13:05 UTC, boorownie commented on src/main/java/nextstep/auth/authentication/SessionAuthenticationInterceptor.java
> +    SessionAuthenticationConverter sessionAuthenticationConverter;
1. 추상화 할 때 어느 하나의 구현 때문에 추상화 되는 부분이 한정되는 것은 꺼려질 수 밖에 없는 것 같아요. 그러면 throws를 붙일지 말지를 고민할 때 하나의 구현으로 결정하기 보다는 추상화된 상태에서 어떻게 처리할 지를 정하는게 더 좋을 것 같아요. AuthenticationConverter.convert() 시 IOException은 필연적으로 발생할 수 있다고 생각하는데요, AuthenticationConverter를 구현하는 쪽에서 각각 예외처리를 해 줄지, 아니면 AuthenticationConverter.convert() 자체에 throws IOException을 붙여서 한 곳에서 처리할 지 결정하는게 좋을 것 같아요. 제 생각에는 각각 예외처리를 하는 것 보다는 throws를 붙여서 한 곳에서 처리하게 하는 것을 선호할 것 같습니다.

2. 이 역시 구현 레벨에 종속되기 보다 추상화 된 레벨에서 어떻게 처리할 지를 먼저 결정하고 그것에 맞게 구현해주는게 좋을 것 같습니다. 저라면 convert하는 과정에서 어떤 예외가 발생할 지 모르니 조금은 범용적인 예외를 thorws하도록 할 것 같습니다.

2022-02-22 13:11 UTC, boorownie approved these changes
피드백 반영된 부분 확인했습니다!
추가로 질문 남겨주신 부분도 확인하여 코멘트 남겨두었어요!
바로 이어서 3단계 미션 진행해주세요~ 🚀

2022-02-22 13:11 UTC, boorownie commented on src/main/java/nextstep/auth/authentication/AuthenticationInterceptor.java
> +		AuthenticationToken token = authenticationConverter.convert(request);
추상화 👍

2022-02-22 13:11 UTC, boorownie commented on src/main/java/nextstep/auth/authorization/SecurityContextInterceptor.java
> +	public boolean preHandle(HttpServletRequest request, HttpServletResponse response, Object handler) throws Exception {
피드백 반영 👍

2022-02-22 13:11 UTC, boorownie commented on src/main/java/nextstep/auth/authentication/SessionAuthenticationInterceptor.java
> -import nextstep.member.domain.LoginMember;
불필요해진 import 제거 👍

2022-02-22 13:11 UTC, merged