Step3: 즐겨찾기 기능 구현
next-step/atdd-subway-favorite pull request #319
Opened 2022-08-06 13:01 UTC by imcool2551

안녕하세요! 3단계 리뷰 잘 부탁드립니다!

2022-08-07 01:11 UTC, catsbi requested changes
imcool2551님  3단계 즐겨찾기 미션 잘 구현해주셨습니다. 
패키지 구조부터 설계를 위해 많은 고민을하고 로직을 작성하신 것 같네요 👍 
피드백 반영들도 잊지않고 잘 해주셨습니다 💯 

이번 미션 즐겨찾기를 진행하시면서, 구간정보를 추가하던 시간을 떠올려봤으면 어떨까 싶습니다. 둘 다 특정 도메인(노선, 유저) 에게 종속되는 개념이라는 점과 영속성 전이, 고아객체라는 개념을 사용하면 서비스나 리포지토리 계층을 별도로 만들지 않고도 핵심 업무 규칙을 적절한 곳에 배치할 수 있을 것 같아요. 

이에 대해 코멘트 남겨드렸으니 확인하시고 다시 리뷰요청 부탁드립니다!

2022-08-07 01:11 UTC, catsbi commented on src/main/java/nextstep/favorite/application/FavoriteService.java
> +public class FavoriteService {
Favorite는 Line의 Section과 같은 개념으로 볼 수 있어요 Member에게 라이프사이클이 모두 종속된 개념이죠. 즉 영속성전이와 고아객체 개념을 사용하면 별도의 서비스, 리포지토리 계층으로 관리하지 않아도 될 것 같습니다.  해당 계층등을 제거해볼 순 없을까요?

2022-08-07 01:11 UTC, catsbi commented on src/main/java/nextstep/favorite/domain/Favorite.java
> +    private Long target;
관계 매핑을 사용해보면 어떨까요?

```suggestion
    private Member member;
    private Station source;
    private Station target;
```

2022-08-07 01:11 UTC, catsbi commented on src/main/java/nextstep/favorite/domain/FavoriteValidationService.java
> +public class FavoriteValidationService {
즐겨찾기가 객체 및 일급컬렉션으로 포장된다면 유효성 검증의 책임을 책임질 더 적절한 클래스를 찾을 수 있지 않을까요?

2022-08-07 01:11 UTC, catsbi commented on src/main/java/nextstep/line/domain/Sections.java
> +            throw new CantDeleteSectionException("구간이 둘 이상일때만 삭제할 수 있습니다.");
매직리터럴은 분리해보는게 어떨까요?

2022-08-07 01:11 UTC, catsbi commented on src/main/java/nextstep/line/ui/LineController.java
> +    public ResponseEntity<LineResponse> createLine(@RequestBody @Valid LineRequest lineRequest) {
Bean Validation 💯

2022-08-07 01:11 UTC, catsbi commented on src/main/java/nextstep/member/application/LoginMemberService.java
>          return User.of(member);
Member 패키지에서 auth 패키지의 User를 의존하네요. Member가 UserDetails를 구현한다면 member를 반환해서 의존성을 끊을 수 있지 않을까요?

2022-08-08 04:15 UTC, imcool2551 commented on src/main/java/nextstep/auth/filters/AuthenticationSavingFilter.java
> +        Authentication authentication = new Authentication(userDetails.getPrincipal(), userDetails.getAuthorities());
인증 이전 단계인 AuthenticationProvider에서 UserDetails를 생성할 수 없으면 예외를 던지기 때문에 null check를 안해도 된다고 생각하는데 제가 놓치고 있는 부분이 있으면 알려주시면 감사하겠습니다!

2022-08-08 04:26 UTC, imcool2551 commented on src/main/java/nextstep/common/BaseEntity.java
> +    private LocalDateTime modifiedDate;
필드의 접근 제어자가 private이고 자식 엔티티에서 해당 필드를 수정할 수 있는 메서드가 없기 때문에 변경 불가능하다고 생각하는데 제가 놓친 부분이 있을까요..??

2022-08-08 09:16 UTC, imcool2551 commented
안녕하세요 한솔님! 피드백을 적용하고 리팩토링하면서 생긴 질문 몇가지만 드려도 될까요?

1. LoginMemberService에서 인증된 유저정보를 반환하기 위해 UserDetails를 구현하는 LoginMember 클래스를 추가했습니다. 
처음에는 Member가 직접 UserDetails를 구현하도록 했다가 인증과 관련된 로직은 유저라는 도메인과는 별도라고 생각해서 분리하는 방향으로 구현해봤습니다. 그런데 구현뒤에 살펴보니, LoginMember의 코드가 auth패키지의 User와 사실상 동일한데 User를 직접 반환해도 괜찮지 않을까라는 생각이 들었습니다..ㅎㅎ 이미 member>auth 방향의 의존성은 존재하기 때문에 괜찮다고 생각하는데 어떻게 생각하시나요?

2. 즐겨찾기(Favorite)를 피드백해주신대로 일급 컬렉션으로 묶은 뒤 Member에게 종속된 객체로 리팩토링했습니다. Favorite은 현재 Member, Station 두 객체와 연결이 되는데 Member와는 `일대다 단방향` 관계를 맺고, Station과는 직접참조보다 `id를 이용한 간접참조`로  연결했습니다. 학습한 바로는 두 방법 모두 쿼리의 효율성에는 저하가 있지만, 각각 다음의 이유로 선택했는데 한솔님의 의견을 듣고싶습니다!

 * `일대다 단방향` 은 `다대일 양방향` 보다 쿼리는 더 발생하지만 데이터 변경(CUD)가 빈번하게 발생하지 않는 상황에서 문제가 될 여지가 적다고 판단했습니다. 객체 양쪽 상태의 일관성을 관리해줄 필요없이 한쪽만 신경쓰면 되는 단방향의 이점이 더 크다고 생각했습니다.
 *  Favorite은 Station과 라이프사이클이 동일하지 않기 때문에 직접 참조를 맺을 경우 객체 그래프가 복잡해질(길어질) 여지가 있다고 판단했습니다. 서비스 레이어에서 추가 작업이 필요하지만 객체가 영향을 미칠 수 있는 범위를 줄여서 복잡성을 낮추는 이득이 더 크다고 판단해서 간접 참조로 구현했습니다.

3. 피드백 해주신대로 에러 메시지를 리터럴로 쓰는대신 다른 방법을 고민해봤습니다. 그동안 메시지를 항상 리터럴로만 써왔기 때문에 당장에 떠오르는 방법 두 가지 `예외 객체의 상수로 만들기` vs `별도의 에러 메시지 상수풀 만들기` 가운데 고민했습니다. 그리고, 예외가 발생하는 이유를 설명하는 메시지는 예외 자체와 밀접한 연관이 있다고 판단해서 상수로 만들었습니다. 혹시 예외 메시지를 관리하는 더 나은 방법이 있을까요?

2022-08-08 11:30 UTC, catsbi approved these changes
imcool2551님 피드백 반영 잘 해주셨네요! 일급 컬렉션에 대한 이해도가 많이 높으신것 같아요 👏
크게 군더더기 없이 즐겨찾기 기능 잘 구현해주셨고, 잊지않고 일급 컬렉션에 대한 테스트 케이스도 작성해주셨네요. 커밋 내역도 상세한게 보기 편했고, 문제가되더라도 롤백하기도 편하겠다는 생각이 들었네요 👍

질문에 대한 답변은 코멘트로 남기도록 하겠습니다. 이번 주차 미션 진행하시느라 고생하셨고, 남은 미션도 화이팅하시길 바랍니다!

2022-08-08 11:30 UTC, catsbi commented on src/main/java/nextstep/auth/authentication/AuthenticationException.java
> +        super(DEFAULT_MESSAGE);
💯

2022-08-08 11:30 UTC, catsbi commented on src/main/java/nextstep/line/application/LineService.java
> +                .orElseThrow(() -> new LineNotFoundException(id));
이런 경우 자바 표준 예외를 던지는게 어떨까요?  자바의 컴파일러상에서 문제가 되지 않지만, 비즈니스적으로 문제가 되는 경우에는 사용자 정의 예외를 던지는게 맞지만, 이 경우 IllegalArgumentException이 더 적절하지 않을까 싶습니다!

2022-08-08 11:30 UTC, catsbi commented on src/main/java/nextstep/auth/filters/AuthenticationSavingFilter.java
> +        Authentication authentication = new Authentication(userDetails.getPrincipal(), userDetails.getAuthorities());
이전 단계에서 예외를 던지겠지만, 해당 메서드는 `AuthenticationProvider`만 사용하는 객체가 아니기에, 다른 자식 클래스에서 예외를 던지지 않을 경우 NPE 발생 여지가 생깁니다! 그렇기에 NPE를 고려할 필요가 있어보여요!

2022-08-08 11:30 UTC, catsbi commented on src/test/java/nextstep/member/domain/FavoritesTest.java
> +class FavoritesTest {
💯

2022-08-08 11:44 UTC, catsbi commented
A1. 굳이 LoginMember 클래스를 추가할 필요가 있을까 싶기는 합니다. 중요한건 인터페이스와 그에 따른 핵심 업무겠죠. UserDetails가 제공해야하는 행위들만 제대로 제공하면되는데 그 행위가 Member에 있는게 적절한가에 대한 고민은 하실수 있을 것 같기는 하네요! 그런데 UserDetail이라는 인터페이스가 제공해야 할 행위가 제가 볼 때는 principal과 credential정도만 제공하는걸로 하면 Member에 있어도 괜찮지 않을까요? Password Match는 Matcher 인터페이스를 만들고 거기서 전략을 제공하는 식으로 해서 다른 객체에게 위임해도 될 것 같아요. 

A2. 많은 고민을 하셨군요. !
직접참조와 간접참조에 대해서는 저도 많이 고민을 해봤었고, 두 방법들을 모두 사용했었는데, 결국 비즈니스적 로직의 흐름에 맞춰서 결정하면 되는 문제 같기는 합니다. 

말씀하신 양방향보다는 단방향이, 다대다보단 다대일이 권장되고 이점이 많습니다. 지금 멤버와 즐겨찾기간의 관계는 말씀하신대로 1:N 단방향이 적절해보입니다. 그리고 즐겨찾기와 전철역간에 관계는 저같은 경우 말씀하신 이유로 간접참조를 했는데, 전혀 문제될건 없어보이지만, 제 생각에 다대일 단방향으로 설계하면 충분할 것 같아보입니다. 그리고 기본적으로 지연로딩이기 때문에, 실제 사용하기전에는 프록시 객체로만 가지고 있어서, 정말 필요한 순간까지는 쿼리를 날리지 않기 때문에 그냥 직접참조를 걸어도 큰 문제는 없어보이네요 ㅎㅎ

A3. 저는 지금 작성해주신 방법을 선호합니다 ㅎㅎ 따로 예외 메세지를 properties등을 통해 관리하는것도 쓰지만, 이는 표준 예외에서 사용하는 방법이고 사용자 정의 예외같은경우에는 가 예외자체가 특수한 예외를 표방하기에 해당 예외 객체 내에 예외 메세지를 상수로 만들어 관리하는 편입니다.

2022-08-08 11:44 UTC, merged