Step3 - 즐겨찾기 기능 추가
next-step/atdd-subway-favorite pull request #326
Opened 2022-08-08 12:55 UTC by MaroKim

안녕하세요 최홍준 리뷰어님 

교육생 김성태 입니다. 

먼저, 저번 미션에도 꼼꼼하게 인수 테스트에 대해 확인해주셔서 감사합니다. 

이번 미션에서 관리자의 토큰이 아닌 일반 사용자로 시도했을 때의 예외상황 처리에 대해 지적해 주신 부분에 대해 우선적으로 적용했습니다

아.. 그리고 저번에 @Mock과 @Valid에 대해 문의 드렸는데 제가 잘못 알고 있던 부분이 있어서.. 금방 처리 했습니다. 

신경써주셔서 감사합니다. 

이번 미션에서 필요한 

1. 즐겨찾기 인수 테스트 정의
2. 즐겨찾기 서비스 단위 테스트 정의
3. 즐겨찾기 기능 구현
을 완료하여 리뷰 요청 드립니다. 

이번에도 잘 부탁드립니다. 

감사합니다. :)

2022-08-09 08:00 UTC, 00hongjun commented on src/main/java/nextstep/favorite/domain/Favorite.java
> +import javax.persistence.*;
application이 커질수록 의존 파악이 힘들어지기 때문에 import에 `*` 사용은 피하는게 좋습니다. 😃

2022-08-09 08:01 UTC, 00hongjun commented on src/main/java/nextstep/favorite/domain/Favorite.java
> +    }
사용하지 않는 생성자네요.
protected로 수정해 보는건 어떨까요?

2022-08-09 08:03 UTC, 00hongjun commented on src/main/java/nextstep/favorite/domain/Favorite.java
> +    }
사용하고 있지 않은 걸로 보이지만 도메인에서 set() 메서드는 피해주세요.
필요하다면 비즈니스가 담긴 이름을 부여하고 일하도록 처리해 보면 좋을 것 같습니다.

2022-08-09 08:04 UTC, 00hongjun commented on src/main/java/nextstep/favorite/domain/FavoriteRepository.java
> +    Optional<List<Favorite>> findByMemberId(Long memberId);
외부 라이브러리에 의존하고 있는데요.
domain 패키지가 아닌 다른 곳에 위치하면 어떨까요?

2022-08-09 08:06 UTC, 00hongjun commented on src/test/java/nextstep/subway/acceptance/FavoritesAcceptanceTest.java
> +    public void canNotRegistFavoriteWithInvalidToken() {
꼼꼼한 테스트 👍

2022-08-09 08:07 UTC, 00hongjun commented on src/test/java/nextstep/subway/acceptance/LineAcceptanceTest.java
> +    @Test
line에도 테스트 추가해 주셨군요 👍

2022-08-09 08:10 UTC, 00hongjun commented on src/test/java/nextstep/subway/unit/FavoriteServiceTest.java
> +public class FavoriteServiceTest {
예외 처리 테스트도 추가해 보면 좋을 것 같습니다 😃

2022-08-09 13:05 UTC, MaroKim commented on src/main/java/nextstep/favorite/application/FavoriteService.java
> +                .orElseThrow(() -> new IllegalArgumentException("CAN_NOT_FIND_FAVORITE"));
좀더 상황에 맞는 예외처리가 가능할것 같습니다. 

수정해보겠습니다. 감사합니다.

2022-08-09 13:05 UTC, MaroKim commented on src/main/java/nextstep/favorite/application/dto/FavoriteResponse.java
> +    private Station target;
앗..  다시 확인해서 수정하겠습니다.

말씀하신 문제점도 찾아보고 수정해보겠습니다

2022-08-09 13:07 UTC, MaroKim commented on src/main/java/nextstep/favorite/application/dto/FavoriteResponse.java
> +    }
필요한 상황에 맞춰 사용할 수 있도록 구성했는데 

해당 부분에 대해 좀더 개인적인 기준에 대해 고민해보겠습니다.

2022-08-09 13:08 UTC, MaroKim commented on src/main/java/nextstep/favorite/application/FavoriteService.java
> +    }
해당 Response Dto 구조에 대해 다시 고민해보겠습니다.

2022-08-09 13:09 UTC, MaroKim commented on src/main/java/nextstep/favorite/domain/Favorite.java
> +    }
넵 참고 해서 수정해보겠습니다!

2022-08-09 13:10 UTC, MaroKim commented on src/test/java/nextstep/subway/unit/FavoriteServiceTest.java
> +public class FavoriteServiceTest {
아 깜박한것 같습니다. 추가해보겠습니다. 감사합니다

2022-08-09 13:11 UTC, MaroKim commented on src/main/java/nextstep/favorite/domain/Favorite.java
> +    }
앗.. 해당 부분도 수정하겠습니다.

2022-08-09 13:11 UTC, MaroKim commented on src/main/java/nextstep/favorite/domain/FavoriteRepository.java
> +    Optional<List<Favorite>> findByMemberId(Long memberId);
아하.. 넵 고민해보고 위치를 수정해보도록 하겠습니다.

2022-08-10 07:22 UTC, MaroKim commented on src/main/java/nextstep/favorite/application/FavoriteService.java
> +                .orElseThrow(() -> new IllegalArgumentException("CAN_NOT_FIND_FAVORITE"));
FavoriteException 이라는 클래스를 생성했습니다. 

@ResponseStatus라는 어노테이션으로 제가 원하는 HttpStauts로 이끌수 있어 좋은 부분인것 같습니다. 

현재는 구조가 단순하고 내용이 많지 않지만 앞으로 개발하는 부분에 있어 리뷰 해주신 부분이 개발 및 테스트에 용이하게 이용할 수 있을것 같습니다. 감사합니다!

2022-08-10 07:26 UTC, MaroKim commented on src/main/java/nextstep/favorite/application/FavoriteService.java
> +    }
해당 부분만 처리할 수 있는 Response Dto를 생성했습니다.

내용을 확인해본 결과 사실 이건 제가 설계를 잘못한게 맞습니다 ㅠ

단순하게 즐겨찾기가 등록되어 있는 지 확인하면 되겠지 하고 만들었는데 생각해보니 그래도 Station에 대한 데이터도 

가져오는게 맞는것 같습니다. 

그래서 스펙을 수정할까 하다가, 리뷰어님께서 말씀해주신 방향대로 해봤습니다. 
꼭 같은 서비스여도 Response Dto가 다를 수 있는 상황은 언제든지 일어날 수 있고 예습삼아 해보자는 마인드로 구성했습니다. 
그래서 기존 레거시 코드는 주석으로 막아두고 나중에 스펙만 변경하여 사용할 수 있도록 해볼까 하는 생각입니다 ㅎㅎ

꼼꼼하게 리뷰 해주셔서 감사합니다.

2022-08-10 07:28 UTC, MaroKim commented on src/main/java/nextstep/favorite/application/dto/FavoriteResponse.java
> +    }
지금은 정적 팩토리 메서드를 제거 했습니다. 

이것도 설계 미스 입니다 ㅠ 
정적 팩토리 메서드를 사용하는 것은 서비스의 특정 메서드의 상황에 따라 응답을 처리할 수 있도록 사용하는 것으로 인지 했습니다.

처음에는 저도 그렇게 하려고 설계를 했었는데.. 하다가 필요없는 내용을 제거하고 나서 
이부분이 제가 제대로 정리 할 생각을 하지 못한것 같습니다. 

감사합니다.

2022-08-10 07:31 UTC, MaroKim commented on src/main/java/nextstep/favorite/domain/FavoriteRepository.java
> +    Optional<List<Favorite>> findByMemberId(Long memberId);
슬랙으로 따로 말씀은 드렸으나 제가 오늘 오후에 추가 작업이 어려울 것 같아  ㅜㅜ

일단 제가 생각한데로 수정했습니다. 

도메인에 어울리지 않는게 어떤것이 있을까 하다가 BaseTimeEntity를 말씀하신게 아닐까 생각이 들어서 

해당 클래스를 유틸 패키지에 따로 분리하였습니다. 

제가 잘못 생각한 부분에 대해서는 힌트를 주시면 다시 해보겠습니다 ㅠㅠ

2022-08-10 07:33 UTC, MaroKim commented on src/main/java/nextstep/favorite/application/dto/FavoriteResponse.java
> +    }
에고.. 사용하지 않는 부분에 대해 자꾸 제대로 확인을 못하는것 같습니다. ㅠ

잘 정리할 수 있도록 하겠습니다.

2022-08-10 07:33 UTC, MaroKim commented on src/main/java/nextstep/favorite/domain/BaseTimeEntity.java
> +public class BaseTimeEntity {
넵 setter에 대해서는 주의 하여 사용하겠습니다. 

감사합니다.

2022-08-10 07:34 UTC, MaroKim commented on src/main/java/nextstep/favorite/domain/Favorite.java
> +import javax.persistence.*;
넵 해당 부분도 사용하는 라이브러리만 명시되도록 수정했습니다.

2022-08-10 12:10 UTC, 00hongjun commented on src/main/java/nextstep/favorite/application/FavoriteService.java
> +    }
API에서 사용하는 dto 특히 response는 변경 처리와 재사용을 조심해서 사용해야 하는 부분이라고 생각해요.
Open API를 제공할 경우, 사용하는 client 입장에서는 API 스펙의 작은 변화가 장애로 이어질 수 있기 때문입니다.
기존에 response dto를 재사용해 주셨는데 id만 값을 세팅했을 경우 나머지 필드인 `source`와 `target`은 null 상태로 응답이 갔을 것 같아 코멘트 드렸습니다 😃

2022-08-10 12:16 UTC, 00hongjun commented on src/main/java/nextstep/favorite/domain/FavoriteRepository.java
> +    Optional<List<Favorite>> findByMemberId(Long memberId);
FavoriteRepository가 JPA라는 기술에 의존되어 있어서 다른 패키지로 이동시켜보면 어떨지에 대해 코멘트 드리려는 의도였습니다 🥲
너무 자세하게 코멘트를 드리면 답을 드리는 것 같아 피하게 되고, 답을 안 드리자니 너무 추상적으로 코멘트가 작성되네요..
FavoriteRepository를 다른 패키지로 이동시켜보면 어떨까요? 
infra, adapter 등이 있을 것 같네요 😃

2022-08-10 12:20 UTC, 00hongjun commented on src/main/java/nextstep/favorite/domain/BaseTimeEntity.java
> +public class BaseTimeEntity {
테이블에 저장되는 row의 생성일, 수정일 같은 경우 application에서 임의로 수정하지 못하도록 하는 방향이 좋을 것 같아 코멘트 드렸습니다. 😃

2022-08-10 16:02 UTC, MaroKim commented on src/main/java/nextstep/favorite/domain/FavoriteRepository.java
> +    Optional<List<Favorite>> findByMemberId(Long memberId);
늦은 시간까지 감사합니다 :-) 

이미 답을 주셔서 좀 민망하긴 하지만.. ㅎㅎ adapter 폴더에 리포지토리 인터페이스를 정리하였습니다.

adapter 폴더로 정하게 된 이유는 이번 미션 전체 중의 핵심중의 하나는 도메인간의 결합성을 줄이는 부분이었고 
해당 부분이 어댑터 패턴을 의미 하였음을 브라운님의 힌트나 우아한 형제의 유튜브 링크를 보고 알게되었습니다. 

리포지토리도 도메인 클래스와 JPA라는 기술을 연결하기 위한 어댑터 인터페이스가 필요한 부분이고 
그게 리포지토리 인터페이스가 아닌가.. 그래서 adapter 폴더를 말씀하신가 아닌가 생각했습니다 
(아니라고 하시면 좀더 공부하겠습니다 ㅎㅎ.. )

2022-08-11 13:07 UTC, 00hongjun requested changes
안녕하세요 성태님
몇 가지 코멘트를 추가로 작성해두었습니다!
확인 부탁드릴께요!!

2022-08-11 13:07 UTC, 00hongjun commented on src/main/java/nextstep/favorite/adapter/FavoriteRepository.java
> +public interface FavoriteRepository extends JpaRepository<Favorite, Long> {
repository들이 adapter 패키지로 이동하였군요 👍

2022-08-11 13:07 UTC, 00hongjun commented on src/test/java/nextstep/subway/acceptance/FavoritesAcceptanceTest.java
> +    }
![image](https://user-images.githubusercontent.com/15880709/184139536-c58c1b63-318f-4112-bcaf-e37b44e038f6.png)
![image](https://user-images.githubusercontent.com/15880709/184139786-801b967a-0dc3-4cfa-87af-2d5f397a88c1.png)

위 사진의 설정으로 테스트 코드를 돌리면 FavoritesAcceptanceTest의 대부분의 테스트가 실패하고 있습니다.
테스트 코드의 에러 로그를 살펴보시고 해결해 보면 좋을 것 같아요 😃

2022-08-12 10:20 UTC, MaroKim commented on src/test/java/nextstep/subway/acceptance/FavoritesAcceptanceTest.java
> +    }
아 이건 생각을 못했네요 ㅠ 
그리고 확인을 해보니 더 확실한 테스트네요 

테스트의 차이점도 공부하면서 작성해보겠습니다. 

감사합니다

2022-08-12 10:20 UTC, MaroKim commented on src/test/java/nextstep/subway/acceptance/FavoritesAcceptanceTest.java
> +    }
아 이건 생각을 못했네요 ㅠ 
그리고 확인을 해보니 더 확실한 테스트네요 

테스트의 차이점도 공부하면서 작성해보겠습니다. 

감사합니다

2022-08-12 10:55 UTC, MaroKim commented on src/test/java/nextstep/subway/acceptance/FavoritesAcceptanceTest.java
> +    }
FavoriteRequest 시 생성자가 없어서 발생하고 있었습니다.

예전에도 관련 에러가 나서 수정했었는데  제가 히스토리를 잊어버렸네요.. 

제가 작업 피시를 왔다갔다 하면서 해당 설정을 생각치 못했던것 같습니다. 

감사합니다.

2022-08-12 10:57 UTC, MaroKim commented on src/main/java/nextstep/favorite/exception/FavoriteException.java
> +@ResponseStatus(HttpStatus.INTERNAL_SERVER_ERROR)
사실 NOT_FOUND를 할까 했다가 그건 웹페이지가 없을때나 쓰는거 아닌가 했었는데.. 

찾아보니까 리소스가 없을때도 사용하는게 맞네요 ㅎㅎ..  그냥 HttpStauts Code 정의를 찾아봤으면 되는건데.. ㅠㅠ 

꼼꼼한 리뷰 감사드립니다~!!

2022-08-13 01:33 UTC, 00hongjun approved these changes
안녕하세요 성태님
리뷰 잘 반영해 주셨네요 👍 
미션 진행하는 동안 고생 많으셨습니다!
다음 미션들도 화이팅하시길 바라겠습니다 🚀🔥

2022-08-13 01:33 UTC, 00hongjun commented on src/main/java/nextstep/favorite/application/dto/FavoriteRequest.java
> +
private 처리해 주시면 좋을 것 같습니다 😃
혹시 이 코멘트 때문에 혼선이 있으셨을까요? https://github.com/next-step/atdd-subway-favorite/pull/326#discussion_r941026917

링크의 코멘트는 `@Entity`로 선언된 class의 사용하지 않는 기본 생성자를 protected로 선언해 주면 어떨까 하는 의도의 피드백이었습니다.
`@Entity`로 선언된 class가 왜 기본 생성자가 필요한지 알아 보시면 도움이 되실 것 같아요.

`FavoriteRequest`는 request에 사용되는 dto로 기본 생성자를 사용하지 않는다면 private 처리해 주어도 되는데요.
이 부분은 controller에서 받는 요청, 응답을 어떻게 dto 객체로 변환하는지를 찾아보시면 도움이 되실 것 같습니다!

2022-08-13 01:34 UTC, merged

2022-08-13 10:08 UTC, MaroKim commented on src/main/java/nextstep/favorite/application/dto/FavoriteRequest.java
> +
아 정말 감사합니다. 제가 회사에서 jpa를 제대로 써볼 기회가 없다보니 많이 사용해보진 못했는데 

제가 작성한 코드를 보시고 왠지 그럴거라 생각해 주셨군요 ㅋㅋ 정말 감사드립니다. 

미션동안 잘 이끌어 주셔서 정말 감사했습니다 :-)