3단계 - 즐겨찾기 기능 구현
next-step/atdd-subway-favorite pull request #333
Opened 2022-08-09 11:37 UTC by realrains

안녕하세요 리뷰어님,

이번 단계에서는 뒤늦게 인수조건을 확인해서 나중에 추가된 테스트가 좀 있네요..!
잘 부탁드립니다

2022-08-10 05:17 UTC, dbeod2 requested changes
안녕하세요. 

3단계 미션 잘 구현해주셨습니다 💯 💯 
고민해보면 좋을 것같아서 소소하게 코멘트 몇가지 남겨두었는데
확인 부탁드립니다. 🙏

2022-08-10 05:17 UTC, dbeod2 commented on src/test/java/nextstep/subway/acceptance/FavoriteAcceptanceTest.java
> +    @DisplayName("즐겨찾기 등록")
로그인 요청 후 실제로 로그인이 되었는지 확인해보면 어떨까요? 

예를 들면 `로그인 요청 -> 로그인 확인 -> 등록 -> 조회` 순으로 테스트해봐도 좋을 것 같습니다 🙏

2022-08-10 05:17 UTC, dbeod2 commented on src/test/java/nextstep/subway/acceptance/FavoriteAcceptanceTest.java
> +        assertThat(response.statusCode()).isEqualTo(HttpStatus.UNAUTHORIZED.value());
상태 응답 확인도 리팩토링 대상이 될 수도 있겠네요 :-) 

```suggestion
      상태_응답_확인(response.statusCode(),HttpStatus.UNAUTHORIZED)
```

2022-08-11 07:50 UTC, realrains commented on src/test/java/nextstep/subway/applicaion/FavoriteServiceTest.java
> +        var userId = 123L;
자주 사용되는 변수여서 픽스처로 공통화하면 좋을 것 같습니다. 테스트를 하나하나 작성하면서 추가하다보니 놓치고 있었네요!

2022-08-11 07:52 UTC, realrains commented on src/main/java/nextstep/subway/applicaion/favorite/exception/InvalidFavoriteOwnerException.java
> +public class InvalidFavoriteOwnerException extends FavoriteException {
`InvalidFavoriteStationException` 의 경우에는 발생하는 상황도 다른 경우가 있어서 메시지를 추가해서 더 명확하게 예외를 정의하는 게 좋은 것 같네요, 수정하도록 하겠습니다!

2022-08-11 07:52 UTC, realrains commented on src/test/java/nextstep/subway/acceptance/FavoriteAcceptanceTest.java
> +        assertThat(response.statusCode()).isEqualTo(HttpStatus.UNAUTHORIZED.value());
이 부분도 말씀주신대로 공통화 해보았습니다 ㅎㅎ

2022-08-11 07:55 UTC, realrains commented on src/test/java/nextstep/subway/acceptance/FavoriteAcceptanceTest.java
> +    @DisplayName("즐겨찾기 등록")
로그인 요청 -> 로그인 확인을 검증하는게 정확히 어떤 방식일지 잘 감이 안와서 일단 매 테스트의 before each 에서 로그인과 로그인 검증을 하고 해당 토큰을 각 등록/삭제 메서드에서 사용하도록 변경해 보았습니다!

한편으로는, 로그인이 제대로 되지 않았다면 권한이 필요한 각 메서드에서 401 예외가 발생할 것이기 때문에 중복된 검증이 아닌가 하는 궁금증이 생기는데요! 별도로 로그인 검증 스텝을 두는 것을 제안해주신 배경이 궁급합니다

2022-08-11 13:00 UTC, dbeod2 commented on src/test/java/nextstep/subway/acceptance/FavoriteAcceptanceTest.java
> +    @DisplayName("즐겨찾기 등록")
인수테스트는 실제 사용자 환경에서 사용자의 입장으로 테스트를 수행을 해야합니다. 
실제 로그인을 한 뒤에 즐겨찾기를 등록한 시나리오와 동일하게 테스트되어야 한다고 생각했습니다. 

말씀주신대로, 로그인이 제대로 되지 않았다면 예외가 발생하지만, 즐겨찾기등록 시나리오에는 로그인이 유효하지 않을 때, 예외가 발생한다는 시나리오도 존재하지 않지 않나요~?

만약, 예외가 발생한다면 작성한 테스트가 실패할 것 같습니다 🙏

2022-08-12 00:22 UTC, dbeod2 approved these changes
마지막 단계까지 피드백 반영 잘해주셨네요 👍 
마지막 미션도 잘 해내실거라 믿고있습니다. 

부족했던 리뷰지만 잘 진행해주셔서 감사합니다 🥺 
마지막 미션 화이팅입니다!👍🏻🏃🏻‍♀️

2022-08-12 00:22 UTC, dbeod2 commented on src/test/java/nextstep/subway/acceptance/FavoriteAcceptanceTest.java
> +    private String 로그인_성공(String email, String password) {
👍 👍 피드백 반영 해주셨네요

2022-08-12 00:22 UTC, dbeod2 commented on src/main/java/nextstep/subway/applicaion/favorite/FavoriteService.java
> +            throw new InvalidFavoriteStationException("즐겨찾기의 출발역과 도착역이 동일합니다.");
어떤 오류인지 명확하게 알 수 있게 되었습니다 🙏

2022-08-12 00:22 UTC, dbeod2 commented on src/test/java/nextstep/subway/applicaion/FavoriteServiceTest.java
> +    private final Long USER_ID = 123L;
👍

2022-08-12 00:22 UTC, merged