[Step3] 리뷰 요청드립니다~!!!
next-step/atdd-subway-favorite pull request #342
Opened 2022-08-15 07:41 UTC by exemeedys

2022-08-15 10:52 UTC, junwoochoi requested changes
안녕하세요!! 벌써 마지막 미션이네요! 👍 
커밋로그를 확인해보니 ATDD + TDD 사이클을 신경써서 미션을 진행하신 게 잘 보이네요 😄 
몇가지 고민해보면 좋을 것 같은 부분을 코멘트로 남겨봤습니다.
한번 고민해보시고 마무리 해보면 도움이 될 듯 합니다!

2022-08-15 10:52 UTC, junwoochoi commented on src/main/java/nextstep/auth/AuthConfig.java
> +    private ObjectMapper objectMapper;
피드백 적용 감사드립니다 :)

2022-08-15 10:52 UTC, junwoochoi commented on src/main/java/nextstep/auth/UserDetails.java
> +    String getPrincipal();
👍

2022-08-15 10:52 UTC, junwoochoi commented on src/main/java/nextstep/favorite/application/FavoriteService.java
> +    }
boolean 리턴이 필요한 이유가 무엇인가요?

2022-08-15 10:52 UTC, junwoochoi commented on src/main/java/nextstep/favorite/domain/Favorite.java
> +    private Station target;
아래 두가지 모두 등록이 가능할 것 같은데 OneToOne이라고 생각하신 이유가 있을까요?
```
강남 - 양재
강남 - 신림
```

2022-08-15 10:52 UTC, junwoochoi commented on src/test/java/nextstep/subway/acceptance/FavoriteAcceptanceTest.java
> +}
다양한 테스트 케이스 검증 👍 👍

2022-08-15 10:52 UTC, junwoochoi commented on src/test/java/nextstep/subway/unit/FavoriteServiceMockTest.java
> +public class FavoriteServiceMockTest {
서비스 테스트도 잊지않고 테스트 👍 👍

2022-08-15 10:52 UTC, junwoochoi commented on src/main/java/nextstep/favorite/domain/Favorite.java
> +    private Long memberId;
Favorite에서 Member를 간접참조하고 있네요 👍
간접 참조는 객체간의 결합도를 끊어낼 수 있는 장점이 있지만, 해당 객체로의 탐색이 조금 더 불편해지는 등의 단점이 존재한답니다.
[발표 영상](https://www.youtube.com/watch?v=dJ5C4qRqAgA&t=3905s) 을 참고해주시면 각 방법의 장단점을 이해할 수 있을 것 같아요 
학습을 위해 직접 참조 형태로 바꾸어 구현해보시면 어떨까요? 😄

2022-08-15 12:31 UTC, exemeedys commented on src/main/java/nextstep/favorite/application/FavoriteService.java
> +    }
정상적으로 삭제한 경우 true를 반환하여 삭제되었다는 것을 알리기 위해 boolean 을 리턴했습니다.

2022-08-15 12:33 UTC, exemeedys commented on src/main/java/nextstep/favorite/domain/Favorite.java
> +    private Station target;
잘못생각하고 있었네요ㅠManyToOne이 적절해보입니다.

2022-08-16 12:08 UTC, junwoochoi approved these changes
피드백 적용해주신 것 확인했습니다!!
마지막 미션까지 열심히 진행해주시느라 고생 많으셨습니다 😄

2022-08-16 12:08 UTC, junwoochoi commented on src/main/java/nextstep/favorite/domain/Favorite.java
> +    private Member member;
피드백 적용👍 
장단점을 느껴보셨길 바랍니다 :)
아무래도 현재 상황에선 Member를 찾아서 바로 Favorite으로 접근하다보니 
Member가 Favorite을 직접 참조하는 쪽이 직접 참조의 장점을 더 느껴볼 수 있었을 것 같네요.
현재 상황에선 최초의 간접 참조가 더 편하다고 느끼셨을 것 같아요~

2022-08-16 12:09 UTC, merged

2022-08-16 12:12 UTC, exemeedys commented on src/main/java/nextstep/favorite/domain/Favorite.java
> +    private Member member;
넵! 말씀하신 대로 Member에서 List<Favorite> favorites를 찾는 방식으로 학습 해봐야할 것 같습니다!