Feat/step2
next-step/atdd-subway-favorite pull request #420
Opened 2023-02-25 10:14 UTC by choi1204

안녕하세요 이번 리뷰도 잘부탁드립니다!!
테스트 컨테이너에서 application.properties 설정한 값이 null로 읽혀져서 삽질을 하다보니 조금 늦어졌습니다. 결국 설정을 제대로 하지 못해 다른 방법으로 우회해서 하였습니다.

fake 컨트롤러관련해서 궁금한점이 몇가지 있어 질문드립니다!
1. 현재 /fake/ 라는 prefix를 주어 새로운 fake 컨트롤러에 요청을 하는 형식으로 진행을 하였는데 이 방법과 똑같은 url을 받는 컨트롤러에 profile을 설정해서 테스트 컨테이너를 실행할때 컨트롤러 빈을 바꿔주는 방법 둘중에 어떤것을 골라야할지 질문드립니다.
2. 위에서 말한것처럼 test/resources/application-test.properties 를 생성해서 값을 주입해도 값을 받지 못했는데 혹시 이에 대해서 말씀주시면 감사하겠습니다!

2023-02-26 08:14 UTC, hjhello423 requested changes
현웅님 안녕하세요. 😀
확인해 보면 좋을 만한 코멘트들을 달아두었는데요.
확인해 보신 후 다시 한번 리뷰 요청 주세요!

2023-02-26 11:28 UTC, choi1204 commented on src/test/java/nextstep/member/AuthAcceptanceTest.java
> +    }
이 부분 테스트 properties 격리가 적용이 안되서 실제 properties에 있는 환경변수를 읽어서 처리해서 에러가 난것같아서 수정햇습니다!

2023-02-26 11:30 UTC, choi1204 commented on src/test/java/nextstep/member/fake/GithubFakeController.java
> +public class GithubFakeController {
github를 실제로 호출하는 부분만 fake로 만들라고 하시는게 이해가 잘 가지 않습니다.
저처럼 fakeController를 만들어서 fake시에 해당컨트롤러를 접근하지 말고 다른 방법으로 처리하라는 말씀이실까요..?

2023-02-26 11:31 UTC, choi1204 commented on src/main/java/nextstep/member/application/GithubClient.java
> +package nextstep.member.application;
외부 api와 통신을 해서 application이 적절하다고 생각햇는데 혹시 어느 레이어에 넣는게 더 적절할까요?

2023-02-26 11:33 UTC, choi1204 commented on src/test/java/nextstep/member/fake/GithubFakeController.java
> +public class GithubFakeController {
추천해주신것처럼 컨트롤러 빈만 교체를 하게 코드를 작성할려고 하니 @profile의 경우 클래스 단위로 적용이 되는데 fake로 교체해주어야 컨트롤러의 메서드들의 경우 관리가 불편하게 되는데 이 점은 어떻게 진행을 해야 할까요

2023-02-27 02:35 UTC, hjhello423 commented on src/test/java/nextstep/member/fake/GithubFakeController.java
> +public class GithubFakeController {
작성해 주신 코드를 보면 `GithubClient`에서 외부와 통신하는 비즈니스를 가지고 있는데요.
GithubClient의 fake를 만들고 이를 이용해 테스트해보면 좋을 것 같습니다. 😀

2023-02-27 02:37 UTC, hjhello423 requested changes
안녕하세요 현웅님
코멘트를 남겨두었는데요. 확인 후 다시 한번 리뷰 요청 주세요!

2023-02-27 02:38 UTC, hjhello423 commented
`LineServiceTest#addSection` 테스트가 실패하고 있어요. 🥲

2023-02-27 02:39 UTC, hjhello423 commented on src/main/java/nextstep/member/application/GithubClient.java
> +package nextstep.member.application;
저는 이런 부분을 infra에 두기도 하는데요.
구현체는 infra에 두고 인터페이스를 만들어 적절한 곳에 두기도 합니다.

2023-03-01 11:34 UTC, choi1204 commented
fakeController에 프로파일 설정을 빠뜨렷군요! 재요청 드리겠씁니다

2023-03-02 06:44 UTC, hjhello423 approved these changes
현웅님 안녕하세요.
모든 테스트 코드가 정상적으로 잘 돌아가네요.
머지하도록 하겠습니다. 다음 step 진행해 주세요. 🚀

2023-03-02 06:44 UTC, merged