Step3-3 리뷰요청
next-step/atdd-subway-favorite pull request #423
Opened 2023-02-26 00:46 UTC by dhlee3994

안녕하세요!!

3단계 리뷰요청 드립니다.😃

감사합니다!

2023-02-26 00:47 UTC, dhlee3994 commented on src/test/java/nextstep/subway/unit/FavoriteServiceTest.java
> +        assertThat(memberA.getFavorites()).isEmpty();
이렇게 검증하는 것이 맞나요? 🤔😭

2023-02-26 14:35 UTC, Flamme1004K requested changes
안녕하세요! 🙇🏻

3단계 미션 잘 구현해 주셨습니다! 💯

몇 가지 코멘트를 남겼으니, 확인 부탁드리겠습니다!

2023-02-26 14:35 UTC, Flamme1004K commented on src/main/java/nextstep/member/application/MemberService.java
> +        return MemberResponse.of(findById(id));
도메인 클래스에 대해서 응답 객체를 통한 함수 사용은 안티 패턴이라고도 합니다. 어떤 이유일까요?

2023-02-26 14:35 UTC, Flamme1004K commented on src/main/java/nextstep/member/domain/Member.java
> +    }
도메인 로직 좋네요 👍👍

2023-02-26 14:35 UTC, Flamme1004K commented on src/main/java/nextstep/subway/applicaion/FavoriteService.java
> +        member.removeFavorite(favorite);
favorite을 생성하는 것은 favorite에게 favorite을 삭제하는 것은 member에게, 둘에 대한 방향성이 다른 이유를 알 수 있을까요?

2023-02-26 14:35 UTC, Flamme1004K commented on src/main/java/nextstep/subway/domain/Favorite.java
> +    private Member member;
직접 참조가 아닌 간접 참조로 변경해 볼까요?

2023-02-26 14:35 UTC, Flamme1004K commented on src/main/java/nextstep/subway/ui/FavoriteController.java
> +    public ResponseEntity<Void> removeFavorite(@Authentication LoginMember loginMember, @PathVariable Long id) {
`@ResponseStatus`를 사용하는 방법도 있겠군요! 😊

2023-02-26 14:35 UTC, Flamme1004K commented on src/test/java/nextstep/subway/acceptance/AcceptanceUtils.java
> +    }
너무 좋네요 👍👍

2023-02-26 14:35 UTC, Flamme1004K commented on src/test/java/nextstep/subway/acceptance/FavoriteAcceptanceTest.java
> +    }
깔끔한 인수 테스트 👍

2023-02-26 14:35 UTC, Flamme1004K commented on src/test/java/nextstep/subway/unit/FavoriteServiceTest.java
> +        assertThat(memberA.getFavorites()).isEmpty();
잘하셨습니다! 👍👍

2023-02-26 14:35 UTC, Flamme1004K commented on src/test/java/nextstep/subway/unit/FavoriteTest.java
> +    }
예외 케이스까지 좋네요 👍👍

예외 케이스 말고 추가에 대한 단위 테스트도 진행하셨으면 좋을 것 같아요. 😊

2023-02-27 02:04 UTC, dhlee3994 commented on src/main/java/nextstep/subway/applicaion/FavoriteService.java
> +        member.removeFavorite(favorite);
출발역, 도착역에 대한 정보를 담고 있어서 subway 패키지 안에 넣었지만, Favorite의 생명주기는 Member가 관리해야 한다고 생각합니다. 
그래서 만약에 Favorite의 Id 값이 필요하지 않았다면 `favoriteRepository.save(favorite);`도 호출하지 않았을 것입니다.

2023-02-27 03:16 UTC, dhlee3994 commented on src/main/java/nextstep/member/application/MemberService.java
> +        return MemberResponse.of(findById(id));
findById(id) 리턴 값이 Member 객체고 이를 Dto로 변환하는 것이라고 생각하는데 말씀하신 부분이 잘 이해가 가지 않습니다 😭

2023-02-27 08:35 UTC, dhlee3994 commented on src/test/java/nextstep/subway/unit/FavoriteTest.java
>  }
도메인 테스트를 최대한 남기는 방법을 생각하다가 `ReflectionTestUtils.setField`를 사용했습니다.
assert 관련 메소드 외에 다른 메소드가 있다는 것이 조금 찝찝해서 도메인 테스트를 삭제해야 하나 고민이 되네요😭

2023-02-27 08:37 UTC, dhlee3994 reviewed
리뷰 반영했습니다!

주신 피드백 중 궁금한 내용과 제 의견은 해당 피드백에 리플 형식으로 남겼습니다!!

감사합니다!😀

2023-02-28 09:18 UTC, Flamme1004K commented on src/test/java/nextstep/subway/unit/FavoriteTest.java
>  }
favorit.validateRemove에 대해서 memberB를 제거할 때 주소값 비교를 통하여 테스트를 할 수도 있을 것 같네요 : )

2023-02-28 09:51 UTC, Flamme1004K approved these changes
안녕하세요! 

피드백 반영 감사합니다. 이만 머지 하도록 하겠습니다. 🤩

그동안 미션 고생하셨습니다. 🙇🏻

2023-02-28 09:51 UTC, Flamme1004K commented on src/main/java/nextstep/subway/domain/Favorite.java
> +    private Long memberId;
간접 참조 👍👍

직접 참조와 간접 참조에 대한 장단점은 무엇일까요?

2023-02-28 09:51 UTC, Flamme1004K commented on src/test/java/nextstep/subway/unit/FavoriteTest.java
> +public class FavoriteTest {
단위 테스트 좋습니다 👍

2023-02-28 09:51 UTC, merged