3단계 - 즐겨찾기 기능 구현
next-step/atdd-subway-favorite pull request #433
Opened 2023-02-28 04:24 UTC by Yunsik-Choi

안녕하세요 준우님 😆
3단계 미션 완료했습니다 리뷰 부탁드립니다!

2023-02-28 13:16 UTC, junwoochoi requested changes
안녕하세요! 3단계 즐겨찾기 기능 구현 잘해주셨습니다!! 😃 
다만 몇가지 더 도전해보고 넘어가면 좋을 것 같은 부분이 있어서 코멘트 남겼습니다.
확인 부탁드립니다!!

2023-02-28 13:16 UTC, junwoochoi commented on src/test/java/nextstep/member/domain/MemberTest.java
> +    }
도메인 테스트 추가 👍

2023-02-28 13:16 UTC, junwoochoi commented on src/main/java/nextstep/member/domain/Favorite.java
> +    private Station target;
Favorite과 관계가 있는 모든 객체를 객체 참조 해주셨네요!
객체 지향적인 설계라는 관점에선 좋을 수 있으나 실제 개발을 할 땐 복잡도를 증가시키는 원인이 될 수 있습니다.
현재는 디비에서 객체를 조회해 올 때 관계를 맺고 있는 모든 객체를 조회해야 합니다.

객체 참조를 이야기 할 때 직접 참조와 간접 참조라는 용어가 있는데요
직접 참조는 객체 참조를 통해서 관계를 표현, 간접 참조는 id값을 통해 참조하는 것을 말합니다.
두 방법에 대해서 고민해보시고 어떤 경우에 간접 참조를 사용하면 더 좋을 지 활용해보면 좋을 것 같아요!

2023-02-28 13:16 UTC, junwoochoi commented on src/main/java/nextstep/member/domain/Favorite.java
> +
현재는 Member를 통해 Favorite에 접근하고 있는데 오히려 반대로 Member 객체는 Favorite필드를 가지고 있지 않고, Favorite에서 Member를 직접 혹은 간접 참조하는 단방향으로 설계해보면 어떨까요?
Member가 불러와질때마다 모든 Favorite이 항상 필요할까요?
각각의 장단점이 있어서 한번 수정해보시면 좋은 경험이 될 것으로 보이네요 :)

2023-02-28 13:16 UTC, junwoochoi commented on src/test/java/nextstep/member/acceptance/FavoriteAcceptanceSteps.java
> +public class FavoriteAcceptanceSteps {
깔끔한 스텝 분리 💯

2023-02-28 13:16 UTC, junwoochoi commented on src/test/java/nextstep/member/acceptance/FavoriteAcceptanceSteps.java
> +    }
둘이 같은 함순데 이름만 다르네요. 아래와 같은 이름은 어떨까요?
```
정상요청이_아닌_경우에_예외_처리한다(response);
```

2023-02-28 13:16 UTC, junwoochoi commented on src/test/java/nextstep/member/acceptance/FavoriteAcceptanceSteps.java
> +    }
여기서도 유효하지 않은 토큰으로 즐겨찾기에 대한 특정 요청을 하는 부분과 검증에 해당하는 부분을 어느정도 나눠서 TEST에서 호출해줘야 더 가독성이 있는 테스트 코드가 되지 않을까 싶은 생각입니다!

2023-02-28 13:16 UTC, junwoochoi commented on src/test/java/nextstep/member/acceptance/FavoriteAcceptanceTest.java
> +    @Nested
👍

2023-03-01 03:52 UTC, Yunsik-Choi commented on src/test/java/nextstep/member/acceptance/FavoriteAcceptanceSteps.java
> +    }
둘이 같은 함수지만 다른 요청을 검증하기 때문에 분리하는 것이 맞다고 생각되는데 준우님 생각은 어떠신가요??

2023-03-01 03:55 UTC, Yunsik-Choi commented on src/test/java/nextstep/member/acceptance/MemberAcceptanceTest.java
> +        유효하지_않은_토큰으로_내_정보를_조회시_예외_처리한다("유효하지 않은 토큰");
인수 테스트는 개발자가 아닌 다른 전문가 분들과 함께 봐야되기 때문에 함수로 빼 네이밍을 해주는 것이 더 좋다고 생각되는데 준우님은 이 부분에 대해서는 어떻게 생각하시나요?

2023-03-01 03:57 UTC, Yunsik-Choi commented on src/test/java/nextstep/member/acceptance/FavoriteAcceptanceSteps.java
> +    }
수정해보겠습니다!

2023-03-02 03:32 UTC, Yunsik-Choi commented
안녕하세요 준우님!
즐겨찾기와 멤버의 직접참조로 간접참조로 변경하는 것은 쉽게 변경이 가능하더라구요!
좋은 경험 시켜주셔서 감사합니다 🙇‍♂️
즐겨찾기 기능이 지하철과 멤버의 바운디드 컨텍스트 밖이라고 생각이 들었습니다.
그래서 즐겨찾기 패키지를 분리하는 방향으로 리팩터링 해봤습니다!

다른 부족한 부분도 있으면 말씀해주시면 수정해보겠습니다!

2023-03-02 14:48 UTC, junwoochoi commented on src/test/java/nextstep/member/acceptance/FavoriteAcceptanceSteps.java
> +    }
다른 요청을 검증하지만 검증하는 부분은 결국 잘못된 요청이 온 것을 확인한다는 부분에서는 같다고 생각되어서 같은 역할이라고 생각되었습니다!

2023-03-02 14:51 UTC, junwoochoi approved these changes
안녕하세요!! 
피드백 드린 부분 잘 고민해보시고 적용해주셔서 감사합니다!
참조 부분도 변경해보시고, 변경된 부분이 더 마음에 드셨다고 하니 좋네요! 앞으로도 각 케이스에 맞는 참조를 적절히 찾아서 활용해보시면 좋겠네요 😄 
바로 머지하겠습니다!

2023-03-02 14:51 UTC, merged