🚀 3단계 - 즐겨찾기 기능 구현
next-step/atdd-subway-favorite pull request #436
Opened 2023-02-28 09:03 UTC by cyPark95

안녕하세요!
3단계 즐겨찾기 기능 구현입니다.

- 즐겨찾기 생성
- 즐겨찾기 조회
- 즐겨찾기 삭제
- 권한이 없는 경우 401 Unauthorized 응답

리뷰 요청 드립니다.☺️

2023-03-01 06:09 UTC, heesunjeong requested changes
3단계 미션 구현 잘 해주셨습니다 👍 👍 
다음 미션 넘어가기 전에 몇가지 조금 더 참고해보시면 좋을 것 같은 부분에 코멘트를 추가했는데요
확인 부탁드려요 :) 🔥 🔥

2023-03-02 11:08 UTC, cyPark95 commented on src/main/java/nextstep/favorite/application/FavoriteService.java
> +    public void deleteFavorite(final Long favoriteId) {
헉! 정말 무지성으로 로직을 짜버렸네요... 부끄럽습니다..

2023-03-02 12:42 UTC, heesunjeong approved these changes
찬영님 피드백 반영 잘 해주셨습니다 💯 💯 
한가지 조금 더 참고해보시면 좋을 것 같은 점을 코멘트 추가했으니, 확인 부탁드려요 :)
이번 미션은 이만 마무리하겠습니다 👏 👏  고생 많으셨습니다!! 마지막 미션까지 꼭 완주하시기를 응원하겠습니다! 화이팅입니다 🔥 🔥

2023-03-02 12:42 UTC, heesunjeong commented on src/main/java/nextstep/favorite/domain/Favorite.java
> +    private Long memberId;
간접참조로 변경해보셨군요! 👍

2023-03-02 12:42 UTC, heesunjeong commented on src/main/java/nextstep/favorite/application/FavoriteService.java
> +        }
```suggestion
        if (!favorite.isMine(member.getId())) {
            throw new IllegalArgumentException(INVALID_AUTHENTICATION_INFO);
        }
```
이런식으로 favorite객체에게 메세지를 보내 확인해보아도 좋을 것 같아요~! 관련해서 아래 글을 참고해보세요!
https://tecoble.techcourse.co.kr/post/2020-04-28-ask-instead-of-getter/

2023-03-02 12:42 UTC, heesunjeong commented on src/test/java/nextstep/member/unit/FavoriteServiceMockTest.java
> +    @DisplayName("즐겨찾기 삭제 실패-다른 사용자의 즐겨찾기")
변경된 기능에 대해서 예외 케이스까지 테스트 잘 작성해주셨습니다 👍

2023-03-02 12:42 UTC, merged