🚀 3단계 - 즐겨찾기 기능 구현
next-step/atdd-subway-favorite pull request #437
Opened 2023-02-28 10:27 UTC by joel-you

리뷰어님 3단계 리뷰 부탁드립니다!

Interceptor 부분은 개발은 했는데 .. 구현이 잘 안되네요 .. 혹시 조언 해주실 수 있으실까요?

2023-03-01 09:08 UTC, pch8388 requested changes
안녕하세요 🙇 
3단계 진행하시면서 전체 테스트를 돌리면 실패하는 부분이 생겼네요 😢 
또한, 요구사항에 충족하지 못하고 있습니다
남겨드린 코멘트 참고하셔서 수정 후 리뷰요청해주세요 🔥

2023-03-01 09:08 UTC, pch8388 commented on src/main/java/nextstep/subway/domain/Favorite.java
> +public class Favorite {
즐겨찾기는 `특정유저`의 즐겨찾기여야 합니다.
`로그인 된 유저`가 즐겨찾기에 추가한 역의 경로를 저장하고자 하는 요구사항입니다 😅

2023-03-01 09:08 UTC, pch8388 commented on src/main/java/nextstep/config/auth/AuthenticationArgumentResolver.java
> +        return jwtTokenProvider.getPrincipal(accessToken);
여기서 토큰을 return 하는 것보다 `AuthenticationContextHolder`에 넣어둔 정보를 꺼내서 세팅할 수 있도록 해보세요 😄

2023-03-01 09:08 UTC, pch8388 commented on src/main/java/nextstep/config/auth/interceptor/AuthenticationInterceptor.java
> +            AuthenticationContextHolder.setAuthentication(accessToken);
토큰을 담아두는 것보다는 `인증정보`를 담아두어야 쓰기 좋습니다 😅

2023-03-01 09:08 UTC, pch8388 commented on src/test/java/nextstep/subway/acceptance/FavoriteSteps.java
> +                .contentType(MediaType.APPLICATION_JSON_VALUE)
꽤나 많이 중복되는 것 같은데, 중복을 제거해보면 어떨까요? 🤔

2023-03-02 13:38 UTC, joelyou-nsuslab commented
위에 PR주신거 다 수정했는데요 .. 한가지 안되는점이 있어서 리뷰요청을 드리지 말아야되지만, 몇시간째 헤딩하고 있어서 .. 문의드립니다ㅠㅠ
/members/{id} 로 되는건 interceptor 에서 exclude 시키고, /members/me 는 include 시키려고 하는데 .. 요게 안되는 방법일까요?

현재 올린 코드처럼 먼저 addPathPatterns 로 /members/me 를 추가하고, excludePathPatters로 /members/** 을 추가하니 전혀 작동을 하지 않는 것 같네용 ....

2023-03-03 08:56 UTC, pch8388 approved these changes
리팩터링 잘해주셨습니다 👍 
남겨드린 코멘트 확인해주세요 😄 
추가로 문의사항 있으시면 DM 으로 말씀해주세요 🔥

2023-03-03 08:56 UTC, pch8388 commented on src/test/java/nextstep/subway/acceptance/RestAssuredAssist.java
> +    public static RequestSpecification given(String accessToken) {
💯

2023-03-03 08:56 UTC, pch8388 commented on src/main/java/nextstep/config/auth/context/Authentication.java
> +import nextstep.member.application.dto.MemberResponse;
auth -> member 의존성을 끊어내보시면 좋습니다 😄 
현재는 MemberController -> auth 패키지 의존 / 여기서 member 패키지 의존을 해서 패키지간 의존성 사이클이 생겼는데요.
어떤 단점들이 있을지에 대해서는 [참고영상](https://youtu.be/dJ5C4qRqAgA?t=2854) 을 보고 공부해보시면 좋습니다 😄

2023-03-03 08:56 UTC, pch8388 commented on src/main/java/nextstep/member/domain/Favorite.java
> +    private Long memberId;
간접참조를 사용해주셨네요 👍 
직접참조와 간접참조를 적절히 잘 사용하면 좋을 것 같습니다 😄

2023-03-03 08:56 UTC, merged