Step3 리뷰 요청드립니다.
next-step/atdd-subway-favorite pull request #487
Opened 2023-07-25 14:50 UTC by 62hoon99

안녕하세요 리뷰어님! 
마지막 단계도 열심히 구현 해보았습니다.

생각나는 케이스는 모두 인수 테스트로 구현 했는데 혹시 다른 케이스를 아신다면 알려주세요!
질문은 코멘트로 달아두었습니다.

감사합니다:)

2023-07-25 14:55 UTC, 62hoon99 commented on src/test/java/nextstep/member/acceptance/FavoriteAcceptanceTest.java
> +    private static final String 마들역명 = "마들역";
여러 테스트 클래스에서 공통적으로 필요한 픽스처들이 있더라고요. Line, Station, Section을 여러 테스트 클래스에서 필요로 하다 보니 중복되는 코드가 점점 늘어나는 것 같습니다. 이렇게 중복되는 코드는 어떻게 해결하는게 좋을까요? 픽스처들을 생성해주는 Factory 클래스를 만들면 될까요? 선호하는 방법이 있으시다면 알고싶습니다!

2023-07-25 15:11 UTC, 62hoon99 commented on src/main/java/nextstep/member/domain/Favorite.java
> +    }
PathFinder.find()는 source와 target의 경로를 찾을 수 없으면 NotConnectedPathException을 발생합니다. 저는 source와 target이 이어져 있지 않으면 예외를 발생시키려고 했습니다. try catch로 NotConnectedPathException을 잡고 FavoriteException을 throw 하는 방식으로 구현을 했습니다. 제가 궁금한 점은 PathFinder.find()를 호출하기만 해도 예외가 발생하는데 try catch로 잡고 다시 예외를 throw 하는 게 괜찮은 방식인지 궁금합니다. 일을 두 번 한다?는 생각이 들어서요. 그리고 Favorite 생성 시에 validation 하기 위해서 Favorite의 생성자를 protected로 제한하고 of 메서드를 사용하도록 강제함으로써 validation을 할 수밖에 만들었는데 이 방법보다 더 좋은 방법이 있는지 궁금합니다.

2023-07-26 10:35 UTC, hjhello423 requested changes
안녕하세요 기훈님
이번 step도 잘 진행해 주셨네👍
간단한 코멘트와 질문에 대한 답변을 작성해두었습니다. 확인 후 다시 한번 리뷰 요청 주세요!

2023-07-26 10:37 UTC, hjhello423 commented on src/test/java/nextstep/member/acceptance/FavoriteAcceptanceTest.java
> +    private static final String 마들역명 = "마들역";
저는 테스트에서 자주 사용되는 데이터들을 관리하기 위해 fixture 클래스를 사용하고 있어요.
fixture를 만들어보고 말씀하신 것들을 관리해 보면 어떨까요? 😀

2023-07-26 10:38 UTC, hjhello423 commented on src/main/java/nextstep/member/domain/Favorite.java
> +    }
우선 해당 exception을 왜 `Favorite`에서 catch하는지에 대해 고민해 보면 좋을 것 같습니다.
NotConnectedPathException은 어디서 처리해야 할까요?

또한 경로가 이어지지 않은 경우에 대한 검증도 이곳에서 하고 있는 것으로 보이는데요.
적절한 책임을 위임했다고 볼 수 있을까요?

2023-07-26 12:43 UTC, 62hoon99 commented on src/main/java/nextstep/exception/notfoundexception/FavoriteNotFoundException.java
> +    public static final String ERROR_MESSAGE = "Favorite 이 존재하지 않습니다.";
넵 좋습니다!

2023-07-26 12:45 UTC, 62hoon99 commented on src/main/java/nextstep/member/application/FavoriteService.java
> +    private MemberRepository memberRepository;
아 final..!! 왜 설정을 안했지! 수정하겠습니다!

2023-07-26 12:56 UTC, 62hoon99 commented on src/main/java/nextstep/member/domain/Favorite.java
> +    private Station source;
객체 참조는 의존성과 결합도를 높이기 때문에 객체 참조가 꼭 필요하지 않다면 사용하지 않는 방향으로 구현하고 있습니다... 라기 보다는 사실 https://youtu.be/dJ5C4qRqAgA 조영호님의 우아한 객체지향 세미나에서 객체 참조를 최소한으로 하라는 말씀을 듣고 진짜 그런지 적용해보는 중입니다. 하하..

2023-07-26 13:01 UTC, 62hoon99 commented on src/test/java/nextstep/member/acceptance/FavoriteAcceptanceTest.java
> +    private Long 부산_이호선_id;
후딱 제거하겠습니다.

2023-07-26 13:05 UTC, 62hoon99 commented on src/test/java/nextstep/member/unit/FavoriteTest.java
> +    void createFavorite() {
아하 @DisplayName 이 그런 용도였군요! 좋습니다!

2023-07-26 13:16 UTC, 62hoon99 commented on src/main/java/nextstep/member/domain/Favorite.java
> +    }
`try catch` 를 사용하지 않고 연결 되어 있지 않은 역이면` PathFinder.find()` 에서 exception 이 발생하게 놔두고 `ControllerExceptionHandler` 에서 처리만 하는게 나으려나요..? 저의 의도는 이 예외가 Favorite를 생성하는 중에 발생했다는 것을 표현하고 싶어서 `try catch` 로 `NotConnectedPathException`을 잡고 `FavoriteException`을 throw 한 거였습니다. 


음 저는 Favorite에서 책임을 지는게 좋다고 생각합니다. Favorite를 생성하는 모든 객체에서 Favorite를 생성하기 전에 경로가 이어져 있다는 검증을 해주지는 않을 것이기 때문에 저는 Favorite의 생성자나 정적 팩토리 메서드에서 검증을 하는게 좋다고 생각해요!

2023-07-26 13:17 UTC, 62hoon99 commented on src/test/java/nextstep/member/acceptance/FavoriteAcceptanceTest.java
> +    private static final String 마들역명 = "마들역";
넵 좋습니다!

2023-07-28 00:31 UTC, hjhello423 commented on src/main/java/nextstep/member/domain/Favorite.java
> +    }
`구간이 연결되어 있지 않다.`는 `즐겨찾기`라는 도메인보다는 `경로`같은 도메인이 가지고 있는게 조금 더 설득력 있어 보이지 않을까 하는 개인적인 의견입니다!
추가로 `즐겨찾기`가 아닌 이전 미션에서 진행했던 `경로 찾기` 기능을 사용할 때도 경로가 연결되어 있지 않은 경우들이 발생하면 어떻게 처리하는게 좋을지도 고민해 보면 좋을 것 같아요 😀

2023-07-28 15:23 UTC, 62hoon99 commented on src/main/java/nextstep/member/domain/Favorite.java
> +    }
넵 감사합니다~! 하지만 저는 '즐겨 찾기의 시작 역과 도착 역이 이어져 있어야 한다'는 즐겨 찾기의 책임이라는 생각이 더 크네요.. 경로같은 다른 도메인에서 가지고 있는다 하면 favoriteService에서 검증을 하게 될 것 같은데 저는 가능하면 service에서 검증을 하지 않는게 좋다고 생각합니다. https://jojoldu.tistory.com/412 요 글에서 아래와 같은 내용이 나오는데요. 이 부분이 제 생각과 흡사합니다.
```
로또 번호가 필요한 모든 장소에선 검증로직이 들어가야만 합니다.
- List<Long> 으로 된 데이터는 모두 검증 로직이 필요할까요?
- 신규 입사자분들은 어떻게 이 검증로직이 필요한지 알 수 있을까요?
등등 모든 코드와 도메인을 알고 있지 않다면 언제든 문제가 발생할 여지가 있습니다.
```
그리고 service에서 검증을 하게 된다면 예외 케이스를 테스트 하기 위해 Service 도 Test 를 해야 해서 번거로워지기도 하고요. 요 부분은 앞으로도 계속 고민해보고 리뷰어님이 말씀해주신 방법으로도 해보고 제 생각대로도 해보면서 알아가 보겠습니다! 감사합니다!

2023-08-04 13:18 UTC, 62hoon99 commented
안녕하세요 리뷰어님! 오랜만에 리뷰 요청 드리네요. 테스트에서 자주 사용되는 fixture 들을 관리하는 클래스를 따로 만드려고 여러 시도를 해보았는데 기존 테스트 코드들을 싹 다 바꾸어야 해서... 계속 미루다가 결국 바꾸지 못하고 리뷰 요청 드립니다. 이런 경험을 통해 각 테스트에서 최대한 비슷한 픽스쳐를 사용한다거나 처음부터 생각하고 만들어야 겠다는 교훈을 얻었습니다... ㅎㅎ 나머지는 최대한 피드백 반영해서 고쳐봤습니다! 감사합니다~~

2023-08-05 11:35 UTC, hjhello423 commented on src/main/java/nextstep/member/domain/Favorite.java
> +    }
앗 저는 서비스에서 검증을 하는 방향으로 피드백 드린 것은 아니었어요.
지금 경로에 대한 validation을 `즐겨찾기` 도메인 에서 하고 있는데요.  경로가 이어졌는지, 경로를 찾을 수 있는 역인지 등에 대한 검증은 `경로` 도메인이 가지고 있는 것이 맞지 않을까 하는 의견이었습니다!

> 경로같은 다른 도메인에서 가지고 있는다 하면 favoriteService에서 검증을 하게 될 것 같은데 
말씀하신 이 부분은 제가 이해가 잘 안됐어요. `경로 도메인`에서 검증을 하면 되는데  왜 `favoriteService`에서 검증이 나오는지에 대한 부분이요.

2023-08-05 11:46 UTC, hjhello423 approved these changes
안녕하세요 기훈님 😀
리뷰 반영해 주신 부분들 확인하였습니다. 
일부 반영 안된 것들과는 별개로 요구 사항에 충족하여서 머지하도록 할게요.
이번 미션은 여기서 마무리하도록 할게요. 미션 진행되는 동안 고생하셨습니다. 
다음 미션들도 화이팅하세요! 🚀🚀

2023-08-05 11:46 UTC, hjhello423 commented on src/main/java/nextstep/member/application/CustomOAuth2UserService.java
> +    private final MemberRepository memberRepository;
다른 곳들도 찾아서 꼼꼼하게 반영해 주셨군요. 👍

2023-08-05 11:46 UTC, hjhello423 commented on src/test/java/nextstep/member/unit/FavoriteTest.java
> +    @DisplayName("Favorite 생성 시 연결되어 있지 않은 역이면 예외처리")
테스트 코드에 대한 이해도가 쉽게 상승할 것 같아요. 😀

2023-08-05 11:47 UTC, merged

2023-08-05 12:52 UTC, 62hoon99 commented on src/main/java/nextstep/member/domain/Favorite.java
> +    }
아하.. 경로 도메인을 생성하면 되는 거였군요.. 저는 따로 Path 클래스를 생성해서 구현하지는 않았어서 오해했네요!