Step3
next-step/atdd-subway-favorite pull request #544
Opened 2023-08-06 05:34 UTC by michaelkimm

안녕하세요! 형준님 좋은 주말입니다! step2 피드백 반영 및 step3 요구 사항 적용 건 PR 보냅니다! 가감 없는 피드백 부탁드립니다🥊!

# 피드백 반영 사항
- [x] [RuntimeException 보다는 인증토큰이 존재하지 않는다는 예외가 좋지 않을까요~?](https://github.com/next-step/atdd-subway-favorite/pull/535#discussion_r1284008587)
- [x] [GithubClient의 인터페이스 구현체를 만들어 추상화시켜볼까요?](https://github.com/next-step/atdd-subway-favorite/pull/535#discussion_r1284013460) 
- [ ] [(BearAuth, GithubAuth 테스트 메소드) 두개를 합쳐도 될 것 같네요!](https://github.com/next-step/atdd-subway-favorite/pull/535#discussion_r1284012782)
    -> 미반영 이유: 댓글 step2 pr 댓글 참조 바랍니다!

# 구현 사항
### 필수
- [x] 요구사항 설명에서 제공되는 추가된 요구사항을 기반으로 즐겨찾기 기능을 구현해주세요.
- [x] 추가된 요구사항을 정의한 인수 조건을 도출하세요.
- [x] 인수 조건을 검증하는 인수 테스트를 작성하세요.
- [x] 예외 케이스에 대한 검증도 포함하세요.
    - 로그인이 필요한 API 요청 시 유효하지 않은 경우 401 응답 내려주기

### 추가
- [x] 비정상 경로로 즐겨찾기 등록하는 경우

<br>

2023-08-06 06:05 UTC, michaelkimm commented on src/main/java/nextstep/subway/service/FavoriteService.java
> +        Member member = getMember(username);
이 부분이 계속 반복되어 `ArgumentResolver`로 뺄가 생각했는데, 그렇게 되면 @Transactional 코드 안에 `@Entity` jpa에 의해 관리되는 엔티티 객체와 아닌 객체가 동시에 존재하게 될 수 있어서 유지 보수에 불편할 것으로 판단했습니다.

2023-08-06 12:03 UTC, Flamme1004K requested changes
안녕하세요!

3단계 미션 고생하셨습니다!

코멘트 확인 후 다시 요청 부탁드립니다.

감사합니다.

2023-08-06 12:03 UTC, Flamme1004K commented on src/test/java/nextstep/subway/acceptance/favorite/FavoriteAcceptanceTest.java
> +public class FavoriteAcceptanceTest extends AcceptanceTest {
Favorite 인수테스트 좋네요~

적절한 `@Nested` 까지 최고입니다. 👍👍

2023-08-06 12:03 UTC, Flamme1004K commented on src/main/java/nextstep/auth/token/oauth2/github/GithubClient.java
> +    GithubProfileResponse getGithubProfileFromGithub(String accessToken) throws ForbiddenException;
피드백 반영 👍

2023-08-07 01:50 UTC, michaelkimm commented on src/main/java/nextstep/subway/ui/FavoriteController.java
> +    ResponseEntity createFavorite(@RequestBody FavoriteRequest request, @AuthenticationPrincipal UserPrincipal userPrincipal) {
@Flamme1004K 확실히 `favorite`는 `member`에 대한 키만 알고 있으면 돼므로, `member`와의 경계를 만들기 위해선 `memberId`로 간접 참조하는 것이 좋겠군요. db 입장에선 직접 참조 방식과 데이터를 저장하는 방법은 같으므로 큰 문제도 없을거거요. 단, 궁금한 것이 있습니다! 

Q1. **`Auth`가 `Member`를 알고 있어도 괜찮을까요?** `@AuthenticationPrincipal`가 `MemberRepository`를 통해 `member`를 조회하기에 여쭤봅니다.
제 생각 A1. `Auth`와 `Member`는 개념 자체로도 서로 강하게 결합되있기에 문제가 없을 거라 판단했어요. 형준님의 생각이 궁금하네요!

2023-08-07 01:54 UTC, michaelkimm commented on src/main/java/nextstep/subway/domain/entity/Favorite.java
> +    Long memberId;
@Flamme1004K 이런 방식으로 `Favorite`이 `Member`를 간접 참조하도록 변경했습니다!

2023-08-07 01:54 UTC, michaelkimm commented on src/main/java/nextstep/subway/domain/entity/Favorite.java
> -    @ManyToOne(fetch = FetchType.LAZY, cascade = CascadeType.PERSIST)
@Flamme1004K `Favorite`을 통해 `Station` 정보가 바뀌면 안된다고 판단해서 `CascadeType.PERSIST`을 삭제했습니다!

2023-08-07 13:32 UTC, Flamme1004K commented on src/main/java/nextstep/subway/domain/entity/Favorite.java
> +    Long memberId;
좋네요! 훌륭합니다!

2023-08-07 13:33 UTC, Flamme1004K commented on src/main/java/nextstep/subway/domain/entity/Favorite.java
> -    @ManyToOne(fetch = FetchType.LAZY, cascade = CascadeType.PERSIST)
크~ 👍👍

2023-08-07 13:42 UTC, Flamme1004K approved these changes
안녕하세요! 민석님

이만 머지하도록 하겠습니다.

고생하셨습니다.

다음 미션도 화이팅입니다! 응원하겠습니다!

2023-08-07 13:42 UTC, Flamme1004K commented on src/main/java/nextstep/subway/service/FavoriteService.java
> +        favoriteRepository.deleteFavoriteByIdAndMemberId(id, memberId);
👍

2023-08-07 13:42 UTC, merged