🚀 3단계 - 즐겨찾기 기능 구현
next-step/atdd-subway-favorite pull request #546
Opened 2023-08-06 08:06 UTC by cohys7

안녕하세요!
2단계 피드백 반영 및 3단계 미션 리뷰 부탁드립니다~
감사합니다 :)

2023-08-06 08:29 UTC, cohys7 reviewed
지난 PR 리뷰 주신 것 중에 궁금한 점이 있어서 다시 질문 드린 부분이 있는데 해당 부분이랑 함께 리뷰 부탁드립니다!
https://github.com/next-step/atdd-subway-favorite/pull/534

2023-08-06 08:29 UTC, cohys7 commented on src/main/java/nextstep/member/domain/Favorites.java
> +    private final List<Favorite> favorites;
Member에 즐겨찾기를 추가하고 나니 멤버 삭제 인수테스트가 테스트 실행 순서에 따라 실패하는 경우가 종종 발생하더라구요..
즐겨찾기 기능에 대한 인수테스트를 먼저 진행하고 난 후에 멤버에 대한 인수테스트를 수행하면
FK 제약 때문에 발생하는 것으로 보이는데 Cascade.REMOVE와 orphanRemoval 조건을 걸어도 계속 에러가 발생하는데
어떻게 처리해야하는지 모르겠네요.. ㅜㅜ
FK 제약 자체를 걸지 않고 처리하는게 좋을까요?

2023-08-07 01:22 UTC, catsbi commented on src/main/java/nextstep/member/domain/Favorites.java
> +    private final List<Favorite> favorites;
일단 Cascade.Remove전략과 orphanRemoval 속성을 같이 쓸 필요는 없어보여요. 고아객체 삭제 조건만 true해놔도 충분할 것 같습니다. 두 전략 다 의존하는 연관 엔티티가 삭제될 경우, 같이 삭제된다는거에서 기능적으로 동일한데 어떤 차이가 있는지도 확인해보면 좋을 것 같습니다. 

그리고, 각각의 테스트가 순서에 따라 성공과 실패가 달라진다는건 테스트간 격리가 안된다는건데, 제가 코드를 봤을때는 격리도 잘 되어 있고 테스트 시작전 beforeEach로 새로운 멤버 생성 후 토큰 발급하는것 까지 잘 되어 있는 것 같은데,   좀 더 명확한 에러 재현케이스를 설명해주시면 좋을 것 같습니다.

2023-08-07 01:47 UTC, catsbi requested changes
채현님 3단계 즐겨찾기 미션 꼼꼼하게 잘 만들어주셨어요. 
몇 가지 피드백과, 문의주신 내용에 대해 코멘트 남겨놨으니 확인 후 리뷰요청 부탁드려요!

2023-08-07 01:47 UTC, catsbi commented on src/main/java/nextstep/auth/principal/AuthenticationPrincipalArgumentResolver.java
> +        } catch (Exception e) {
RuntimeException, Exception, Thorwable과 같은 최상위 예외는 사용을 지양해주세요. 
실제 발생하는 예외들이 다 포괄적인 최상위 예외에 묻혀서 실제 예외정보들이 묻히거나 우리가 의도하지 않은 예외가 발생했을때도 catch문이 다 잡아버려서 발견을 늦게하는 문제가 생길 수 있습니다

2023-08-07 01:47 UTC, catsbi commented on src/main/java/nextstep/member/application/FavoriteService.java
> +        }
findPath는 경로탐색용 로직으로 보이는데, 여기서는 경로가 있는지 확인 후 예외 발생 목적으로 보여요. 🤔 경로찾기 내부의 몇몇 로직을 사용할 목적으로 (ex: 경로가 유효한지) 사용하는데, 검증만을 위한 함수가 아니기에 나중에 기획변경 및 로직변경으로 해당 코드까지 같이 영향이 갈 수 있어서, 주의할 필요가 있습니다.

2023-08-07 01:47 UTC, catsbi commented on src/main/java/nextstep/member/application/FavoriteService.java
> +    @Transactional
Transactional의 기본 readOnly전략은 false에요 
서비스 계층의 함수는 기본적으로 트랜잭션으로 구분되고, 기본전략은 readOnly=false입니다. 
그래서 클래스레벨에서 readOnly정책을 true로 바꿔주고 쓰기 기능 로직에 readOnly를 false로 해주거나 아예 서비스를 분리하거나 하는 방식을 사용할 수 있겠죠. 

CQRS패턴을 확인해보면 좋을 것 같아요

2023-08-07 01:47 UTC, catsbi commented on src/main/java/nextstep/member/domain/Favorite.java
> +        if (this == o) return true;
한 줄짜리 분기문도 블럭`{}` 생략은 지양하는게 좋아요. IDE에 의해 자동생성된 코드도 예외는 아닙니다.

2023-08-07 01:47 UTC, catsbi commented on src/test/java/nextstep/member/acceptance/FavoriteAcceptanceTest.java
> +class FavoriteAcceptanceTest extends AcceptanceTest {
인수테스트인만큼 즐겨찾기를 생성하고, 조회한다음 수정하고, 삭제까지하고, 그 다음 다시 삭제를 시도하면서 실패하는 것까지 하나의 흐름으로 진행되는 인수테스트 케이스도 작성해보면 어떨까요?

2023-08-07 09:03 UTC, cohys7 commented on src/main/java/nextstep/member/domain/Favorites.java
> +    private final List<Favorite> favorites;
두 옵션 모두 부모 엔티티가 삭제되면 자식 엔티티가 삭제되는데
부모 엔티티에서 자식 엔티티를 제거할 때는
Cascade.REMOVE는 자식 엔티티가 그대로 남아있는 반면
orphanRemoval는 자식 엔티티가 제거 되네요.

말씀 주신데로 Cascade.REMOVE는 사용하지 않고 orphanRemoval만 사용하도록 수정했습니다.

https://github.com/next-step/atdd-subway-favorite/pull/546/commits/e84da8d852940b29fb442da8d1049c172521d9a1

---
테스트가 실패하는 경우에 대해서 좀 더 설명드리면
아래와 같이 멤버 인수테스트를 진행할 때는 정상적으로 테스트가 성공하지만,
<img width="417" alt="스크린샷 2023-08-07 오후 5 55 12" src="https://github.com/next-step/atdd-subway-favorite/assets/86863306/8130cd1c-1acf-4aba-a718-1329e482b994">
즐겨찾기에 대한 인수 테스트 이후 멤버 인수 테스트 시 에러가 발생하는데요.
<img width="416" alt="스크린샷 2023-08-07 오후 5 55 28" src="https://github.com/next-step/atdd-subway-favorite/assets/86863306/491413a8-20de-42d7-b071-36823048ce78">

디버깅을 해보면 아래와 같이 에러가 발생합니다.
<img width="910" alt="스크린샷 2023-08-07 오후 5 58 10" src="https://github.com/next-step/atdd-subway-favorite/assets/86863306/2bd04c6b-29fa-4c0c-bd70-52f4fde91546">

회원 삭제시 favorite 테이블의 fk 제약 조건 때문에 실패하는 것 같다는 생각이 드는데요.
테스트 전 모든 테이블을 truncate하고 정리해주는데 왜 문제가 발생하는지 잘모르겠습니다 ㅜㅜ

2023-08-07 09:17 UTC, cohys7 commented on src/main/java/nextstep/member/domain/Favorite.java
> +        if (this == o) return true;
자동 생성되는 코드를 놓쳤네요ㅎㅎ
Intelij에서 제공하는 기능들이 편리한 부분이 있는데 주의해서 봐야할 것 같네요!
수정했습니다~

https://github.com/next-step/atdd-subway-favorite/pull/546/commits/15911e662646a0eb0e2c2e224c843e046ef17714

2023-08-07 09:24 UTC, cohys7 commented on src/test/java/nextstep/member/acceptance/FavoriteAcceptanceTest.java
> +class FavoriteAcceptanceTest extends AcceptanceTest {
하나의 인수테스트에서 하나의 기능만 테스트한다고 생각하면서 인수조건을 만들었는데,
범위를 크게해서 하나의 시나리오로 한 번에 여러 기능을 테스트하는 것도 좋은 방법인 것 같네요!
새로운 인수 테스트를 추가해보았습니다!

https://github.com/next-step/atdd-subway-favorite/pull/546/commits/0721970ff502a12d60135fc7f3dc8dcc4f0f8b85

지금까지 미션을 진행하면서 각 기능이나 예외 케이스에 대해 인수 테스트를 여러개 만들었는데요.
만약 지금 처럼 큰 흐름으로 진행되는 인수테스트가 있다면,
예외적인 케이스를 제외하고 각각 기능에 대한 인수 테스트는 별도로 하지 않아도 괜찮은 걸까요?

2023-08-07 09:55 UTC, cohys7 commented on src/main/java/nextstep/member/application/FavoriteService.java
> +        }
경로 조회를 해서 예외 케이스가 발생한 경우에 throw 하면 되지 않을까 생각했는데
validation하는 부분에 대한 것을 별도로 가져가야할 것 같네요.
해당 부분에 대한 체크는 SubwayMap 내부에서 진행하도록 수정 했습니다~

https://github.com/next-step/atdd-subway-favorite/pull/546/commits/9348a17c241f84e64f31985a93cb393ac8ebf34b

2023-08-07 10:00 UTC, cohys7 commented on src/main/java/nextstep/auth/principal/AuthenticationPrincipalArgumentResolver.java
> +        } catch (Exception e) {
JwtToken 파싱시 발생하는 에러를 잡으려고 Exception을 작성했는데,
필요한 Exception만 캐치하도록 수정 했습니다!

https://github.com/next-step/atdd-subway-favorite/pull/546/commits/30a41d2fd84cb5ba954b9b6497ec09359759d6f7

2023-08-07 10:14 UTC, cohys7 commented on src/main/java/nextstep/member/application/FavoriteService.java
> +    @Transactional
변경이 발생하는 명령과 그렇지 않은 쿼리에 대해서 서비스 자체를 분리하니 훨씬 관리가 깔끔해지는 것 같아요.
https://github.com/next-step/atdd-subway-favorite/pull/546/commits/d53358e7d5a624655275a68ce68e3844363cc888

실제로 조회하는 부분의 경우에는 다른 클래스에서 사용하는 경우도 많고,
별도로 서비스 레이어에서 테스트가 필요한 경우도 적은데 분리하니 이점이 많아지는 것 같네요.

2023-08-08 14:02 UTC, catsbi commented on src/test/java/nextstep/member/acceptance/FavoriteAcceptanceTest.java
> +class FavoriteAcceptanceTest extends AcceptanceTest {
음 여유가된다면 다 작성해도 좋겠지만 그게 안된다면 선택일 것 같은데, 개인적으로는 제가 여기서 권장드린 방법(코멘트)은 인수테스트와 통합테스트 그 어딘가 중간인것 같아서 우선순위는 좀 더 낮을 것 같긴 합니다 ㅎㅎ

2023-08-08 14:12 UTC, catsbi requested changes
채현님, dm으로도 말씀드렸지만, 피드백 반영 잘 해주셔서 크게 코멘트 남길 부분은 없는데, 테스트 실패나는 부분에 대해서 코멘트 및 dm남겨드렸으니 확인 및 수정 후 다시 리뷰요청 부탁드려요!

2023-08-08 14:12 UTC, catsbi commented on src/main/java/nextstep/auth/principal/AuthenticationPrincipalArgumentResolver.java
> +        } catch (JwtException | IllegalArgumentException e) {
👍

2023-08-10 14:53 UTC, cohys7 commented on src/main/java/nextstep/member/domain/Favorites.java
> +    private final List<Favorite> favorites;
확인 감사합니다! 양방향 매핑 관계여야 영속성 전이가 되는군요!
변경하고 나니 테스트가 잘 동작하네요~

https://github.com/next-step/atdd-subway-favorite/pull/546/commits/a545e60c1380180d1931275d48aba230d7fa7d1f

2023-08-11 12:22 UTC, catsbi approved these changes
이제 일급 컬렉션의 영속성 전이도 정상적으로 잘 수정된 것 같네요 👍 
미션 진행하느라 고생 정말 많으셨어요! 이만 머지하도록 하겠습니다!

2023-08-11 12:22 UTC, merged