Step3: 리팩토링
next-step/atdd-subway-favorite pull request #570
Opened 2024-02-17 04:05 UTC by samkimpepper

피드백 반영했습니다! 이번에도 코드 리뷰 잘 부탁드립니다!

2024-02-17 04:13 UTC, samkimpepper commented on src/main/java/nextstep/auth/application/LoginMemberService.java
> +}
UserDetailsService를 만들면 UserDetails도 새로 정의해야해서 저는 기존에 있던 LoginMember를 활용하는 방향으로 구현해봤습니다. 사실 TokenService에서 MemberService를 바로 쓰는게 아니라 UserDetailsService를 통해서 하도록 추상화해야할 이유를 잘 모르겠습니다. 무엇 때문인가요? 저는 LoginMemberService로 추상화해서 바뀐 점을 잘 모르겠고 의존을 감췄다는 느낌밖에 들지 않습니다.

2024-02-17 04:13 UTC, samkimpepper commented on src/main/java/nextstep/auth/application/TokenService.java
> +        }
나중에 새로운 OAuth2 로그인이 추가될 것을 고려해서 이렇게 구현해봤는데 어떤가요...?!

2024-02-18 00:54 UTC, pch8388 requested changes
3단계 구현 빠르게 해주셨는데, 요구사항을 충족하지 못한것 같아요 😢 
코멘트 확인하셔서 수정 후 리뷰요청해주세요 🔥

2024-02-18 00:54 UTC, pch8388 commented on src/main/java/nextstep/auth/application/LoginMemberService.java
> +}
> 인증 관련 부분을 다른 프로젝트에서 재사용 할 수 있는 수준으로 리팩터링 하세요

이번 단계의 요구사항을 보면 위와 같은 데, `다른 프로젝트에서 재사용 할 수 있는 수준` 이 되려면 어떻게 해야할까요? 🤔 
일단은 auth 가 다른 패키지에 의존하지 않도록 해야합니다 
member 는 현재 우리가 개발한 지하철 즐겨찾기 기능이 들어간 애플리케이션에 맞추어 개발된 패키지입니다
따라서, auth 에서 member 에 대한 의존성을 제거해주셔야 합니다 😅 
의존성에 사이클이 생기기 시작하면, 많은 클래스 / 패키지들이 서로 의존하게 될 수 있고, 그런 관계들이 많아지기 시작하면 결국 작은 변경에도 전체 애플리케이션이 혼란에 빠질 수 있습니다 😢 

그렇기 때문에 OOP 를 학습하다보면 꽤나 많은 원칙이 의존성을 어떻게 제거할까에 대해 고민하는 모습을 많이 볼 수 있습니다

2024-02-18 00:54 UTC, pch8388 commented on src/main/java/nextstep/auth/application/TokenService.java
> +//    public TokenResponse createTokenFromGithub(String code) {
미사용 주석은 삭제해주세요 👀

2024-02-18 00:54 UTC, pch8388 commented on src/main/java/nextstep/auth/application/TokenService.java
> +        }
좋은 시도라고 생각합니다 😄 
다만 현재 메소드에서 드러날 필요 없는 로직이라고 생각됩니다 🤔 
메소드 추출해보시는 건 어떤가요?

2024-02-18 00:54 UTC, pch8388 commented on src/test/java/nextstep/member/utils/GithubTestController.java
> +        }
[Enum](https://techblog.woowahan.com/2527)을 좀 더 활용해보시는 건 어떨까요? 🤔 
링크 확인하셔서 리팩토링 해주세요 🔥

2024-02-18 00:54 UTC, pch8388 commented on src/main/resources/application.properties
> +<<<<<<< HEAD
👀

2024-02-18 00:54 UTC, pch8388 commented on src/main/java/nextstep/member/ui/AuthenticationPrincipalArgumentResolver.java
>  package nextstep.member.ui;
`AuthenticationPrincipalArgumentResolver` 는 인증 로직이라고 생각되는데, member 가 인증로직을 알고 있어야 할까요? 🤔

2024-02-18 01:45 UTC, samkimpepper commented on src/main/java/nextstep/auth/application/LoginMemberService.java
> +}
여기서 어떻게 더 의존성을 제거해야될지 잘 모르겠습니다! ㅠㅠ 구체적으로 설명해주실 수 있을까요?

2024-02-18 01:46 UTC, samkimpepper commented on src/main/java/nextstep/auth/application/TokenService.java
> +        }
앗 어떻게 추출하면 될까요...?

2024-02-18 21:41 UTC, pch8388 commented on src/main/java/nextstep/auth/application/LoginMemberService.java
> +}
3단계 힌트에 포함된 [영상](https://www.youtube.com/watch?t=2941&v=dJ5C4qRqAgA&feature=youtu.be) 에서도 자세히 설명하고 있는 데, UserDetailsService 라는 인터페이스를 만들어서 auth 에 두고, member 에서 해당 인터페이스를 구현하도록 해둡니다. 이후 spring 을 이용해 해당 bean 을 주입하게 되면, 의존성을 끊어 낼 수 있습니다 😄

2024-02-18 21:42 UTC, pch8388 commented on src/main/java/nextstep/auth/application/TokenService.java
> +        }
```java
OAuth2UserRequest oAuth2UserRequest = method(String code, String provider);
```

이런형태를 생각했습니다 😄

2024-02-21 05:02 UTC, samkimpepper commented
어떻게 해야할지 모르겠어서 결국 샘플 코드 참고해서 리팩토링했습니다. 거의 샘플 코드와 비슷하긴 한데 다른 점은, UserDetails와 OAuth2User에 id 필드를 추가한 부분과 oauth2 패키지를 token 패키지와 분리한 부분입니다. oauth2 패키지가 token 패키지에 속하는 것이 잘 납득이 안 가서 분리했습니다. 

궁금한 점이 있습니다. auth에는 인터페이스를, 구현체를 member에 둬서 의존성을 해결했다고 하는 것 같긴 한데 이게 정말로 분리되었다고 볼 수 있을지 잘 모르겠습니다! 결국 인터페이스를 통해 간접적으로 의존하게 되는 것 아닌가요? 이런 구조를 분리되었다라고 말할 수 있는 이유를 설명해주시면 감사하겠습니다! 결국 UserDetailsService, OAuth2UserService의 구현체도 하나밖에 없는데 이렇게 분리하는 이유가 궁금합니다. 여기서 어떻게 확장되길래 이렇게 분리하는지 잘 모르겠습니다! 👀

2024-02-21 11:23 UTC, pch8388 approved these changes
리팩토링 잘해주셨네요 👏 
코멘트 드린 부분은 참고만 해주시면 될 것 같습니다 😄 
미션 진행 고생 많으셨습니다. 
추가로 이야기 하고 싶으신 부분은 DM 부탁드립니다 🚀

2024-02-21 11:23 UTC, pch8388 commented on src/main/java/nextstep/auth/oauth2/OAuth2User.java
> +import nextstep.member.domain.Member;
미사용 import 는 삭제해주세요 👁️

2024-02-21 11:23 UTC, pch8388 commented on src/main/java/nextstep/auth/token/TokenService.java
> +        String token = jwtTokenProvider.createToken(userDetails.getId(), userDetails.getUsername());
이부분 때문에 UserDetails 에도 getId 를 넣으신것 같은데, ID 를 꼭 넘겨야 하나요? 🤔 
email 로도 충분하지 않을까요? 😅

2024-02-21 11:23 UTC, pch8388 commented on src/main/java/nextstep/auth/oauth2/OAuth2User.java
> +package nextstep.auth.oauth2;
> oauth2 패키지가 token 패키지에 속하는 것이 잘 납득이 안 가서 분리했습니다.

패키지 분리는 채림님께서 원하시는 대로 하셔도 좋습니다 😄 
아마도 샘플코드에서 의도한 것은 [rfc6749](https://datatracker.ietf.org/doc/html/rfc6749#section-1.2) 에서 보는 것과 같이 oauth2 스펙 자체가 access token 을 기반으로 설계 되었기 때문에, token 패키지에 속하는 개념이라고 생각하고 구현한 것이라고 생각됩니다.

2024-02-21 11:23 UTC, pch8388 commented on src/main/java/nextstep/auth/userdetails/UserDetailsService.java
> +public interface UserDetailsService {
> 궁금한 점이 있습니다. auth에는 인터페이스를, 구현체를 member에 둬서 의존성을 해결했다고 하는 것 같긴 한데 이게 정말로 분리되었다고 볼 수 있을지 잘 모르겠습니다! 결국 인터페이스를 통해 간접적으로 의존하게 되는 것 아닌가요? 이런 구조를 분리되었다라고 말할 수 있는 이유를 설명해주시면 감사하겠습니다! 결국 UserDetailsService, OAuth2UserService의 구현체도 하나밖에 없는데 이렇게 분리하는 이유가 궁금합니다. 여기서 어떻게 확장되길래 이렇게 분리하는지 잘 모르겠습니다! 👀

[SOLID](https://catsbi.oopy.io/ded9db4f-6ed6-48c7-9d46-8a0d88b1b6d0) 라고 부르는 것 중 DIP 라는 것에 대한 이야기입니다. 
구체적인 것보다 추상적인 것에 의존하자는 것인데요
추상적인 것에 의존하면 확장성을 가질 수 있게 되는데, 이것은 [영상](https://www.youtube.com/watch?v=26S4VFUWlJM&t=4243s) 에 잘 설명되어 있습니다. 정말 좋은 강의니 꼭 한번 보시기 바랍니다. 😄 

클래스와 마찬가지로 패키지도 의존성 사이클을 만들지 않는 것이 좋습니다.
의존성이 있다는 것은 변경에 영향을 받을 가능성이 있다는 것인데, 사이클이 돌면 서로 영향을 많이 주고 받게 될 가능성이 높아집니다.
따라서, 추상적인 `인증 패키지`가 구체적 `멤버 패키지` 에 의존하지 않는 것이 좋습니다

2024-02-21 11:24 UTC, merged