🚀 1단계 - 즐겨찾기 기능 완성
next-step/atdd-subway-favorite pull request #610
Opened 2024-02-25 13:11 UTC by SUBIN606

2024-02-26 01:08 UTC, dbeod2 requested changes
안녕하세요. 
즐겨찾기 미션 잘 진행해주셨네요 👍 

소소하게 코멘트 남겨두었는데 확인 부탁드립니다 🙏🏻

2024-02-26 01:08 UTC, dbeod2 commented on src/main/java/nextstep/favorite/domain/Favorite.java
> +    private Long memberId;
Favorite에서 Member를 간접참조를 하고있네요 ~
 
간접 참조는 객체간의 결합도를 끊어낼 수 있는 장점이 있지만, 해당 객체로의 탐색이 조금 더 불편해지는 등의 단점이 존재한답니다.
[발표 영상](https://www.youtube.com/watch?v=dJ5C4qRqAgA&t=3905s) 을 참고해주시면 직접/간접참조의 장단점을 이해할 수 있을 것 같아요 😃

학습차 직접참조로 구현해보시는걸 추천드립니다~

2024-02-26 01:08 UTC, dbeod2 commented on src/test/java/nextstep/favorite/acceptance/FavoriteAcceptanceTest.java
> +    @DisplayName("즐겨찾기 삭제")
자신의 즐겨찾기가 아닐 경우 즐겨찾기 제거에 실패 할 수 있을 것 같습니다.
해당 테스트도 추가해보면 좋을 것 같아요 🙏🏻

2024-02-26 01:08 UTC, dbeod2 commented on src/test/java/nextstep/favorite/acceptance/FavoriteAcceptanceTest.java
> +    @DisplayName("즐겨찾기 생성")
비로그인시 즐겨찾기를 생성한다면 어떻게 될까요? 🤔
여러가지 예외케이스에 대해 고민해보시고 테스트해보면 좋을 것 같습니다.

2024-02-26 01:08 UTC, dbeod2 commented on src/test/java/nextstep/favorite/acceptance/FavoriteApiRequester.java
> +public class FavoriteApiRequester {
💯

2024-02-27 12:49 UTC, SUBIN606 commented on src/main/java/nextstep/favorite/domain/Favorite.java
> +    private Long memberId;
제가 평소에 직접참조를 더 많이 사용했어서, 일부러 간접참조로 구현해봤습니다! 이건 그대로 유지해도 될까요?!

2024-02-27 20:26 UTC, dbeod2 commented on src/main/java/nextstep/favorite/domain/Favorite.java
> +    private Long memberId;
앗 그러면 그대로 유지해주셔도 좋을 것 같아요 👍

2024-02-27 20:28 UTC, dbeod2 approved these changes
안녕하세요! 
피드백 반영 빠르게 해주셨네요 👏🏻👏🏻👏🏻
해당 PR 바로 머지하겠습니다 다음미션도 화이팅해주세요~ 💪🏻💪🏻💪🏻

2024-02-27 20:28 UTC, dbeod2 commented on src/test/java/nextstep/favorite/acceptance/FavoriteAcceptanceTest.java
> +    class 즐겨찾기_생성 {
예외 상황 테스트도 추가해주셨네요 💯

2024-02-27 20:28 UTC, dbeod2 commented on src/main/java/nextstep/favorite/application/FavoriteService.java
> +        return favoriteRepository.save(new Favorite(member.getId(), sourceStation.getId(), targetStation.getId())).getId();
👍

2024-02-27 20:28 UTC, merged