🚀 3단계 - 패키지 리팩터링
next-step/atdd-subway-favorite pull request #654
Opened 2024-03-06 18:03 UTC by xonic789

기존 인수 테스트들을 활용하여 리팩토링 진행하였습니다.

Auth 와 Member의 의존을 분리 진행했습니다.

- Auth 와 Member 는 서로를 아예 모르게 구현 진행하였습니다.
- 서로 Http Api 로 통신하도록 구현했습니다
  - 구현에 의존하지 않도록 java interface 를 활용하여 구현 진행했습니다.

하다보니 욕심이 생겼지만 시간이 없어서 추가 못한 기능이 있습니다.
1. `MemberController`에서 `PatchMapping` API 부분 고려해야할 점
  - `password` 단방향 암호화 필요합니다.
  - `password` 가 `null` 일 시에 `OAuth2` 벤더로 가입했는지 확인 필요합니다.

2024-03-08 03:46 UTC, testrace requested changes
안녕하세요 승우님 😃 
3단계 잘 구현해 주셨네요 👍 
몇 가지 코멘트 남겨두었는데요 확인해 주시고 다시 리뷰 요청 부탁드려요

2024-03-08 03:46 UTC, testrace commented on src/main/java/nextstep/auth/application/GithubLoginService.java
> +        }
코드상 try catch 구문을 제거하더라도 컴파일 에러는 발생하지 않는데요
userGetter의 구현체에서 exception 이 발생할거란건 미리 알지 못하면 코드를 이해하기 어려운 것 같아요

userGetter에서 반드시 rest template을 활용하는 것이 보장되어 있다면 interface에서 throws 구문을 추가하면 어떨까요?
인터페이스에 예외를 명시한다면 포괄적인 Exception 대신 구체적인 예외 클래스를 활용해볼 수 있을 것 같아요

2024-03-08 03:46 UTC, testrace commented on src/main/java/nextstep/auth/infra/UserGetterImpl.java
> +            response = restTemplate.exchange(url, HttpMethod.PATCH, requestEntity,
메서드명이 getUser라서 http method도 GET일거라 예상했는데 PATCH네요
승우님은 PATCH method를 어떤 경우에 사용하시는지 궁금합니다 🤔

2024-03-08 03:46 UTC, testrace commented on src/main/java/nextstep/auth/infra/UserGetterImpl.java
> +        HttpEntity<String> requestEntity = new HttpEntity<>(null, headers);
RestTemplate 객체는 하나만 만들어두고 재사용할 수 있을 것 같아요
HttpHeaders 등의 설정도 중복되는 코드도 제거하면 어떨까요?

2024-03-08 03:46 UTC, testrace commented on src/main/java/nextstep/exception/BadRequestException.java
> +    public static final String MEMBER_PASSWORD_MISMATCH = "멤버의 비밀번호가 일치하지 않습니다.";
MEMBER_NOT_FOUND의 메시지와 통일성 있게 '회원'이라는 표현은 어떨까요?

2024-03-08 03:46 UTC, testrace commented on src/main/java/nextstep/member/application/MemberService.java
> +            // OAuth2 벤더를 통해서 로그인 한 경우이므로, 벤더 체크 후 회원 정보 반환
'password == null' 이라는 조건이 oauth와 관련이 있다는 사실은 주석을 통해 알 수 있네요 👍 
모든 상황에서 통용되는게 아니라면 조금 더 직관적인 로직을 구성하면 어떨까 싶네요

2024-03-08 03:46 UTC, testrace commented on src/main/java/nextstep/properties/AppProperties.java
> +    public static class UserService {
(참고만해주세요)
Service라는 네이밍이 마치 `@Service`에서 얘기하는 서비스 계층인가 라고 생각했어요
properties에 service가 왜 필요하지라는 생각이 들었는데요
MSA의 서비스일거라 추측되네요 😃 

개인적으로 Service 대신 다른 네이밍을 고민해볼 것 같아요(저의 스타일과는 달라서 떠오르는 네이밍은 없네요 😅)

2024-03-12 13:52 UTC, xonic789 commented on src/main/java/nextstep/auth/infra/UserGetterImpl.java
> +            response = restTemplate.exchange(url, HttpMethod.PATCH, requestEntity,
저는 API에서 Member라는 어떠한 Resource가 있다고 가정할 때
굳이 데이터를 모두 내려줄 필요가 없을 때 사용합니다.
사실 실무에서는 잘 사용하지 않고, 사용할 수 있을 때 사용하는 것 같네요 ㅎㅎ.

2024-03-12 14:13 UTC, xonic789 commented on src/main/java/nextstep/properties/AppProperties.java
> +    public static class UserService {
넵 맞습니다. 
다른 애플리케이션 서버를 일컬어서 Service라고 붙였고 설정파일에서 주입하도록 했어요.
url이라던지, 이런 부분들은 언제든 바뀔 수 있는 부분이라 생각해서 애플리케이션 코드를 건들이고 싶지 않았어요.
저도 이름은 고민이 되네요.. ㅎㅎ

2024-03-12 14:14 UTC, xonic789 commented on src/main/java/nextstep/member/application/MemberService.java
> +            // OAuth2 벤더를 통해서 로그인 한 경우이므로, 벤더 체크 후 회원 정보 반환
음.. 이 단계 미션에서는 패키지 분리만 진행한다고 자세하게 고민은 해보지 않았는데요.
아마 한다면 단방향 암호화된 문자열로 특정한 상황에만 쓸 수 있는 API로 만들 것 같습니다.!

2024-03-12 14:15 UTC, xonic789 commented
피드백 반영 완료했습니다 :)
너무 늦어서 죄송해요ㅠㅠ

2024-03-13 10:34 UTC, testrace approved these changes
안녕하세요 승우님 😃 
피드백 반영 잘해주셨네요 👍 
3주차 미션은 마무리하겠습니다!
이제 미션 하나만 남았으니 끝까지 완주하시길 바라겠습니다 🔥

2024-03-13 10:34 UTC, merged