1단계 - 즐겨찾기 기능 완성
next-step/atdd-subway-favorite pull request #662
Opened 2024-07-23 00:43 UTC by giwankim

안녕하세요! 앞으로 한 주간 잘 부탁드리겠습니다. 🙇 

즐겨 찾기 기능 및 테스트를 단위 테스트와 인수 테스트에 나눠서 구현해 보았습니다.

2024-07-23 12:26 UTC, catsbi requested changes
지완님 반갑습니다. 3번째 미션을 함께 하게 된 이한솔입니다.  👏 
1단계 미션 잘 진행해주셨어요. 

이전 주차 미션들의 내용은 이미 피드백을 받고 반영한것으로 간주해서 제외하고 피드백을 드렸습니다. 
몇 가지 부분들 체크한 뒤 다시 리뷰요청 부탁드려요!

2024-07-23 12:26 UTC, catsbi commented on src/main/java/nextstep/favorite/application/FavoriteService.java
> +  private final FavoriteRemover favoriteRemover;
즐겨찾기에 대한 usecase별로 컴포넌트가 나온것 같은데, 이렇게 해야 할 이유가 있을까요? 
헥사고날 아키텍처를 고려해보기엔 usecase에 대한 추상화가 부족해보이고, 기능별 분리라고 하기에는 내부 구현체의 로직에 별다른 로직이 없습니다.  보통 목적에 따라 컴포넌트 분리하는것은 하나의 클래스에서 책임지기에 너무 사용성이 많아지면서 가독성이 떨어지고, usecase가 특징적으로 분리되야해서 분리되는 경우에 컴포넌트 분리를 수행하는데, 지금은 그럴 필요가 없어보입니다 🤔

2024-07-23 12:26 UTC, catsbi commented on src/main/java/nextstep/favorite/application/FavoriteService.java
> +    return favoriteMapper.mapToFavoriteResponse(savedFavorite);
- 개행을 좀 해서 개념간 분리를 해보면 가독성이 좋아질 것 같습니다. 
- validate는 말 그대로 예외만을 던지기위한 검증기인데, 이 부분들은 사실 바로 예외를 던지기보단 반환 타입을 논리값 혹은 예외 메세지를 반환하도록 하여 예외를 던지는건 여기서 직접 하는게 어떨까요? 함수명부터 검증이지, 검증 및 예외던짐은 아니니까요!

2024-07-23 12:26 UTC, catsbi commented on src/main/java/nextstep/favorite/ui/FavoriteController.java
> +  @PostMapping("/favorites")
`/favorites` 리소스는 컨트롤러 레벨로 올려도 좋을 것 같네요 ㅎㅎ

2024-07-23 12:26 UTC, catsbi commented on src/test/java/nextstep/favorite/acceptance/FavoriteAcceptanceTest.java
> +class FavoriteAcceptanceTest extends AcceptanceTest {
권한이 없는 요청일 경우 401 예외를 반환받는 인수 테스트도 있으면 좋을 것 같네요!

2024-07-23 12:26 UTC, catsbi commented on src/test/java/nextstep/member/acceptance/AuthAcceptanceTest.java
>  class AuthAcceptanceTest extends AcceptanceTest {
토큰정보가 위변조되었거나 계정정보가 틀린경우에 대한 테스트도 있으면 좋을 것 같아요!

2024-07-24 02:08 UTC, giwankim commented on src/test/java/nextstep/favorite/acceptance/FavoriteAcceptanceTest.java
> +class FavoriteAcceptanceTest extends AcceptanceTest {
인증/인가 관련 테스트를 `FavoriteServiceTest` 와 `FavoriteControllerTest` 에서 커버하고 있어서 인수 테스트 테스트 케이스로 추가하지 않았습니다.

그리고 리뷰해 주신 `AuthAcceptanceTest` 에서 테스트를 추가함으로써 공통적인 인증 테스트가 커버되고 있다고 판단됩니다.

그래도 `FavoriteAcceptanceTest` 작성이 필요할까요?

2024-07-24 09:20 UTC, catsbi commented on src/test/java/nextstep/favorite/acceptance/FavoriteAcceptanceTest.java
> +class FavoriteAcceptanceTest extends AcceptanceTest {
음 고민되는 부분이긴합니다. 일단, 저는 controller입장에서 API를 테스트할때, service에서 테스트할 때 domain에서 테스트할 경우 내용이 겹치더라도 모두 작성하는 편이긴 합니다. 근데 필수라고까지 생각이 들진 않네요. 편하신대로 하시죠!

2024-07-24 09:25 UTC, catsbi approved these changes
지완님 피드백 반영까지 빠르게 잘 해주셨어요. 훨씬 보기 편해졌네요! 
몇 가지 고민해보면 좋은 코멘트와 함께 머지드립니다. 다음 단계 진행하면서 같이 고민해보시죠!

2024-07-24 09:25 UTC, catsbi commented on src/main/java/nextstep/favorite/application/FavoriteService.java
> +    }
이럴경우 함수명의 접두사에 is나 has, exitst와 같은 논리값 반환을 유추할 수 있는 함수명으로 만들면 가독성이 더 좋아질꺼에요 👍

2024-07-24 09:25 UTC, catsbi commented on src/main/java/nextstep/favorite/application/FavoriteService.java
> +        favoriteRepository.findById(id).orElseThrow(() -> new FavoriteNotFoundException(id));
예외를 어째서 `FavoriteNotFoundException`로 던져야 하는지에 대한 이유를 고민해보면 좋을 것 같아요. 
해당 식별자(id)를 통해 조회를 해서 결과가 없는 경우 id가 잘못되었다는것을 의미하는데요. 보통 매개변수가 잘못되어 예외가 발생하는 경우 IllegalArgumentException을 던집니다. 그리고 이런 예외는 자바 자체에서 정한 일반적인 규격이기에 대부분의 자바 개발자가 숙지하고 있어 유지보수 및 가독성 측면에서 더 높습니다. 

그럼에도 FavoriteNotFoundException를 던져야 하는 이유가 명확하게 있는게 아니라면, 일반적인 예외를 던지는것을 권장드려요!

저는 보통 해당 서비스의 기획 및 요구사항에 맞지 않는 비즈니스 오류일 경우 커스텀 예외를 사용하곤 합니다!

2024-07-24 09:25 UTC, catsbi commented on src/main/java/nextstep/member/application/JwtTokenProvider.java
> +      return Jwts.parser().setSigningKey(secretKey).parseClaimsJws(token).getBody().getSubject();
객체지향 생활체조원칙의 4번째 규칙은` 규칙 4: 한 줄에 점을 하나만 찍는다.` 입니다. 
즉 디미터 법칙을 지키라는 의도인데요. 이를 확인해보면 좋을 것 같아요!

2024-07-24 09:25 UTC, catsbi commented on src/test/java/nextstep/member/acceptance/AuthAcceptanceTest.java
> +      })
검증 케이스 꼼꼼하게 💯

2024-07-24 09:25 UTC, merged