인수 테스트와 인증/step 3
next-step/atdd-subway-favorite pull request #686
Opened 2024-08-09 18:03 UTC by santos019

안녕하세요~

쉽지 않았지만, 할 수 있는 만큼 추상화를 진행해보았습니다..
이번 리뷰도 잘 부탁드립니다~

감사합니다.

2024-08-10 06:01 UTC, seondongpyo requested changes
안녕하세요, 민정님!
잘해주셨는데 미션 요구사항 중 충족되지 않은 부분이 있는 것 같아요.
요구사항과 힌트를 참고하여 리팩터링 진행해주시면 좋을 것 같습니다.
주말 잘 보내시고, 조금만 더 힘내주세요 🔥

2024-08-10 06:01 UTC, seondongpyo commented on src/main/java/nextstep/member/application/TokenService.java
>  public class TokenService {
해당 클래스는 인증과 관련된 클래스인데, 현재 우리가 직접 정의한 `member` 패키지에 의존하고 있어요.
이번 요구사항은 `인증 관련 부분을 다른 프로젝트에서 재사용 할 수 있는 수준으로 리팩터링` 하는 것인데,
인증과 관련된 클래스들을 `auth` 패키지로 분리하고, `auth` 패키지가 `member`에 의존하지 않도록 해보면 어떨까요?

2024-08-10 06:01 UTC, seondongpyo commented on src/main/java/nextstep/member/application/UserDetailsService.java
> +public interface UserDetailsService {
`UserDetailsService`는 인증과 관련된 인터페이스로 만들어보시면 좋을 것 같아요.

2024-08-10 06:01 UTC, seondongpyo commented on src/main/java/nextstep/member/application/GithubClient.java
> +public class GithubClient implements ClientRequester {
해당 클래스도 GitHub 로그인, 즉 인증과 관련된 클래스이니, `member` 패키지에 의존하지 않도록 해보면 어떨까요?

2024-08-10 15:06 UTC, santos019 commented
안녕하세요~~
저번 리뷰는 제가 이상하게 해와서 많이 당황하셨겠네요.. 죄송합니다.
제가 이해를 잘못했더라구요..! 다시 해봤는데.. 이번에는 요구사항에 적합했으면 좋겠네요!!

우선 Auth 패키지에 있는 것들은 인증에 관한 역할만 가지는 것이 옳다고 생각하여, Auth 이외의 역할들은 UserDetailsService로 넘겼습니다. 
UserDeatilsService에는 아래 2개의 메서드를 선언해놨습니다.

  1. AuthMember findAuthMemberByEmail(String email);
  2. AuthMember findAuthMemberOrOtherJob(ProfileResponse profileResponse);

findAuthMemberByEmail는 필수적으로 쓰이는 메서드입니다. 
findAuthMemberOrOtherJob는 UserDetailsService에서 별도의 다른 작업이 필요할 때 그 상황에 맞춰 사용하려고 만든 메서드입니다.  

그리고 GitClient는 ProfileResponse를 Auth 패키지로 옮기면서 자동적으로 Member에 대한 의존도가 사라졌다고 판단하여, 별다른 수정을 하지 않았는데요. 이게 옳은 판단이었으면 좋겠습니다..!

감사합니다!!

2024-08-11 01:18 UTC, seondongpyo approved these changes
피드백 반영 잘해주셨네요 👍 
몇 가지 코멘트와 함께 이번 미션은 여기서 merge 하겠습니다.
그동안 미션 진행하시느라 고생 많으셨습니다 🙇

2024-08-11 01:18 UTC, seondongpyo commented on src/main/java/nextstep/auth/application/TokenService.java
> +    private ClientRequester clientRequester;
구현 클래스가 아닌 인터페이스들에 의존하도록 잘 변경해주셨네요 👍

2024-08-11 01:18 UTC, seondongpyo commented on src/main/java/nextstep/auth/application/TokenService.java
> +    private UserDetailsService memberService;
변수 이름을 인터페이스 이름에 맞춰서 지어보면 어떨까요?

2024-08-11 01:18 UTC, seondongpyo commented on src/main/java/nextstep/auth/application/UserDetailsService.java
> +    AuthMember findAuthMemberOrOtherJob(ProfileResponse profileResponse);
> findAuthMemberOrOtherJob는 UserDetailsService에서 별도의 다른 작업이 필요할 때 그 상황에 맞춰 사용하려고 만든 메서드입니다. 혹시 이렇게 하는 것 보다 더 나은 구현이 있었을까요?

지금과 같은 구조라면 만약 해당 인터페이스를 다른 프로젝트에서 사용하려고 할 때 별도의 다른 작업이 필요하지 않은 경우에도 해당 메서드를 오버라이딩 할 수밖에 없기 때문에, 개인적으로는 인터페이스를 따로 분리해서 처리하는 게 낫지 않을까 생각합니다.

2024-08-11 01:18 UTC, seondongpyo commented on src/main/java/nextstep/converter/MemberConverter.java
> +    public static AuthMember MemberToAuthMember(Member member) {
메서드 이름은 소문자로 시작하도록 작성해보면 어떨까요?
```suggestion
    public static AuthMember memberToAuthMember(Member member) {
```

2024-08-11 01:18 UTC, seondongpyo commented on src/main/java/nextstep/member/application/MemberServices.java
> +public interface MemberServices {
인터페이스 이름을 `MemberService` 정도로 지어보면 어떨까요?

2024-08-11 01:18 UTC, merged

2024-08-11 12:48 UTC, santos019 commented on src/main/java/nextstep/auth/application/UserDetailsService.java
> +    AuthMember findAuthMemberOrOtherJob(ProfileResponse profileResponse);
음 필요하지 않은데도 오버라이딩해야하는 문제점이 있었군요.. 이 부분은 조금 더 생각을 해봐야겠습니다. 감사합니다!